README.md
=> Fix README.md Third-party module title name

.github/workflows/build.yml, build.gradle, fixture-monkey-autoparams/build.gradle, fixture-monkey-engine/build.gradle, fixture-monkey-jackson/build.gradle, fixture-monkey-kotlin/build.gradle, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyExtensions.kt, fixture-monkey-mockito/build.gradle, fixture-monkey-starter/build.gradle, fixture-monkey/build.gradle, gradle/wrapper/gradle-wrapper.properties
* branch 전략에서 설정한 branch에도 build script를 적용합니다
* 다양한 자바 버전 빌드 결과를 확인합니다
resolves https://github.com/naver/fixture-monkey/issues/37
=> Enhance build script

build.gradle
main branch 는 0.4.0-SNAPSHOT 이기에 수정합니다.
=> Bump up 0.4.0-SNAPSHOT

build.gradle, fixture-monkey-autoparams/build.gradle, fixture-monkey/src/test/resources/logback.xml
테스트에서 불필요한 Validator debug 로그가 계속 찍혀서 테스트 스콥에 logback.xml 설정을 추가
=> Add logback.xml to remove testing validator debug log

.github/auto_assign.yml, .github/workflows/auto-assign-action.yml
resolves https://github.com/naver/fixture-monkey/issues/51
=> Add Auto Assign

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryTree.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java
dirty 상태가 아닌 경우 build 결과를 캐싱합니다.
=> Add caching when not dirty

README.md, build.gradle, fixture-monkey-kotlin/build.gradle, fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/test/PrimaryConstructorArbitraryGeneratorTestSpecs.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitrarySpecAny.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryValue.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ContainerSizeConstraint.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/DefaultIterableSpec.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/StringAnnotatedArbitraryGenerator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ArbitraryCustomizeTestSpecs.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ArbitraryGeneratorTestSpecs.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ComplexManipulatorTestSpecs.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTestSpecs.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/SimpleManipulatorTestSpecs.java
=> Bump up jqwik 1.6.0 release

content/en/docs/v0.3.x/Examples/Manipulator/ComplexManipulator.md
branch 수정해서 올립니다.
https://naver.github.io/fixture-monkey/docs/v0.3.x/examples/manipulator/complexmanipulator/
```java
@Test
void zip(){
// given
FixtureMonkey fixture = FixtureMonkey.create();
ArbitraryBuilder<String> stringArbitraryBuilder = this.sut.giveMeBuilder(String.class);
ArbitraryBuilder<Integer> integerArbitraryBuilder = this.sut.giveMeBuilder(Integer.class);
// when
ArbitraryBuilder<String> actual = ArbitraryBuilders.zip(
stringArbitraryBuilder,
integerArbitraryBuilder,
(integer, string) -> integer + ". " + string
);
then(actual.sample()).contains(".");
}
```
this.sut -> fixture
=> Fix docs Complex manipulator Zip example

content/en/docs/v0.3.x/Third-party Modules/FixtureMonkeyAutoParams.md, content/en/docs/v0.3.x/Third-party Modules/FixtureMonkeyJackson.md, content/en/docs/v0.3.x/Third-party Modules/FixtureMonkeyKotlin.md, content/en/docs/v0.3.x/Third-party Modules/FixtureMonkeyMockito.md
문서의 3rd party version을 0.3.1로 업데이트 합니다.
=> Update third party module version

.github/auto_assign.yml
=> Rename reviewer ah.jo to seongside

README.md
한국어 문서를 README에 추가합니다.
Maintainer들도 README에 추가합니다.
=> Update Readme add multi-language docs and maintainers

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/CollectionBuilders.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/QueueBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTestSpecs.java
Queue를 생성하는 QueueBuilder를 추가합니다
=> Add supports generating Queue

fixture-monkey-api/build.gradle, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/IntrospectorArbitraryGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/IntrospectorTimeArbitraryGenerator.java
- Arbitrary 를 시작하는 디폴트 Arbitrary 를 제공하는 인터페이스를 추가합니다.
- IntrospectorArbitraryGenerator 에서 제공되는 기본 Arbitray 를 기반으로 ArbitraryIntrospector 에서 조작을 수행합니다.
=> Introduce IntrospectorArbitraryGenerator interfaces

tool/naver-checkstyle-suppressions.xml
=> Add suppress java doc warning

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryTree.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryValue.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ArbitraryGeneratorTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ComplexManipulatorTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTestSpecs.java
Arbitrary 생성에 사용하는 RandomGenerator를 구현하여 Arbitrary가 지원하는 모든 메소드를 지원하도록 수정합니다.
=> Add RandomGenerator for compatibility with Arbitrary

fixture-monkey-autoparams/src/main/java/com/navercorp/fixturemonkey/autoparams/customization/FixtureMonkeyCustomizer.java, fixture-monkey-autoparams/src/test/java/com/navercorp/fixturemonkey/autoparams/test/FixtureMonkeyValueCustomizerTest.java
- fixturemonkey-autoparams 를 사용할때 테스트에서 커스텀 FixtureMonkey 객체를 설정하는 방법을 테스트에 보완합니다.
=> Add test setup with autoparams

fixture-monkey-api/build.gradle, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryIntrospectorResult.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/CompositeArbitraryTypeIntrospector.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryIntrospectorResultTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/CompositeArbitraryTypeIntrospectorTest.java
외부의 타입 생성을 사용자가 정의할 수 있는 ArbitraryTypeIntrospector 을 Composite 으로 구성할 수 있는 CompositeArbitraryTypeIntrospector 를 추가합니다.
=> Introduce CompositeArbitraryTypeIntrospector

README.md, build.gradle, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/IntrospectorTimeArbitraryGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/TimeArbitraryIntrospector.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/generator/JacksonArbitraryGenerator.java, fixture-monkey-kotlin/build.gradle, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/generator/PrimaryConstructorArbitraryGenerator.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/ArrayBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/BeanArbitraryGenerator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/BuilderArbitraryGenerator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/BuilderFieldArbitraries.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/ConstructorPropertiesArbitraryGenerator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/FieldReflectionArbitraryGenerator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/ListBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/MapBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/QueueBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/SetBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/StreamBuilder.java
- jqwik 1.6.3
- `Builders.withbuilder` 의 에러 버그가 수정되어 교체
=> Bump up jqwik 1.6.3

fixture-monkey-autoparams/build.gradle, fixture-monkey-autoparams/src/test/java/com/navercorp/fixturemonkey/autoparams/test/FixtureMonkeyValueCustomizerTest.java
=> Bump up AutoParams 0.3.1 version

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryTypeIntrospector.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryTraverser.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryTree.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTestSpecs.java, tool/naver-checkstyle-rules.xml
checkstyle UnusedImports module을 추가합니다.
=> Add checkstyle module UnusedImports

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/CompositeProperty.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/property/CompositePropertyTest.java
- CompositeProperty 를 추가합니다.
- getter 메소드 정보를 가진 PropertyDescriptorProperty 와  매칭되는 필드 정보를 가진 FieldProperty 를 Composite 으로 관리합니다.
=> Introduce CompositeProperty

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/customizer/KArbitraryCustomizer.kt, fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyExtensionsTest.kt
[sam](https://kotlinlang.org/docs/fun-interfaces.html) 하고 [trailing lambda](https://kotlinlang.org/docs/lambdas.html#passing-trailing-lambdas)를 쓸 수 있게 sam interface로 변경합니다.
=> Make KArbitraryCustomizer sam interface

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java
다음과 같은 작업을 합니다.
1. 불필요한 변수 제거
2. 메소드 순서 조정
3. 개행으로 변경 가능한 변수 분리
4. deprecate할 메소드 명시
=> Polish ArbitraryBuilder

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryNode.java
다음과 같은 작업을 합니다.
1. inner static class 순서를 [convention](https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html)에 따라 조정
2. inner static class prefix를 Fixture에서 Arbitrary로 변경 
3. 메소드 순서 조정, 단순 getter, setter를 뒤에 배치합니다.
4. https://github.com/naver/fixture-monkey/pull/122 를 적용하면서 사용하지 않는 `fixedAsNull` 변수를 제거
=> Polish ArbitraryNode

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryIntrospectorContext.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryTypeIntrospectorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationArbitraryIntrospectorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationTimeArbitraryIntrospectorTest.java
ArbitraryIntrospectorContext 의 속성을 Property 로 교체합니다.
=> Refactor ArbitraryIntrospectorContext with property

fixture-monkey-api/build.gradle, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/IntrospectorTimeArbitraryGenerator.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/CompositeArbitraryTypeIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/IntrospectorTimeArbitraryGeneratorTests.java, fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationTimeArbitraryIntrospector.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationTimeArbitraryIntrospectorTest.java
시간 관련 Arbitrary 의 기본 Range 를 설정합니다.
=> Implements IntrospectorTimeArbitraryGenerator default range

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryProperty.java
확장할 수 있는 ArbitraryGenerator 인터페이스를 추가합니다.
기존의 ArbitraryGenerator 를 대체할 예정입니다.
=> Introduce ArbitraryGenerator interface

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt, fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGeneratorJavaTestSpecs.java, fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGeneratorTestSpecs.kt, fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGeneratorsTest.kt
ExpressionGenerator에서 Boolean을 처리할 수 있도록 합니다
=> Add ExpressionGenerator boolean supports

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/type/TypesTest.java
=> Introduce Types utils getGenericsTypes

fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationBooleanIntrospector.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/BooleanIntrospectorSpec.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/ByteIntrospectorSpec.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationBooleanIntrospectorTest.java
기본 BooleanTypeIntrospector 를 delegate 하여 javax validation annotation 을 적용한 JavaxValidationBooleanIntrospector 를 추가합니다.
=> Introduce javax validation boolean introspector

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaArbitraryTypeIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryTypeIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/TimeArbitraryIntrospector.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaArbitraryTypeIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaArbitraryTypeSpec.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryTypeIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryTypeSpec.java
Java 기본타입과 Java 시간 타입을 묶어 처리하는 JavaArbitraryTypeIntrospector 를 추가합니다.
=> Introduce JavaArbitraryTypeIntrospector

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/type/TypesTest.java
TypeReference 에서 구체화된 Generics 로 Field 의 구체화된 Type 을 가진 ParameterizedType 을 반환하는 유틸 메소드를 추가합니다.
=> Add Types resolveWithTypeReferenceGenerics method

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryApply.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ComplexManipulatorTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ComplexManipulatorTestSpecs.java
apply가 중첩됐을 때 이전 apply의 결과가 무시되는 문제를 해결합니다
=> Fix resampled when nested apply

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryTypeIntrospectDelegatorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryTypeIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaArbitraryTypeIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryTypeIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/matcher/ExactMatcherTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/property/PropertyCacheTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/type/TypesTest.java, fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyJacksonArbitraryGeneratorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationArbitraryIntrospectorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationBooleanIntrospectorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationConstraintGeneratorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationTimeArbitraryIntrospectorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationTimeConstraintGeneratorTest.java
하위 Property 목록을 만드는 메소드를 추가합니다.
=> Add PropertyCache getProperties method

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java
필드 하나의 표현식을 만드는 ExpressionGenerator 확장함수를 추가합니다.
=> Add extensions for ExpressionGenerator

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryTypeIntrospectDelegator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BooleanTypeIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/CompositeArbitraryTypeIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/EnumTypeIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaArbitraryTypeIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryTypeIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/UuidTypeIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/ExactTypeMatcher.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/Matchers.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/TypeMatcher.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryTypeIntrospectDelegatorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaArbitraryTypeIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryTypeIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/matcher/ExactMatcherTest.java
- 파라미터를 Type 으로 변경하고, 이름을 TypeMatcher 로 변경합니다.
=> Rename TypeMatcher with type

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/PropertyValue.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorContextTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/generator/ArbitraryPropertyTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryTypeIntrospectDelegatorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryTypeIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaArbitraryTypeIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryTypeIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/matcher/ExactMatcherTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationArbitraryIntrospectorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationBooleanIntrospectorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationConstraintGeneratorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationTimeArbitraryIntrospectorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationTimeConstraintGeneratorTest.java
ArbitraryProperty 에 propertyValue 를 추가합니다.
=> Refactor ArbitraryProperty with propertyValue

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt, fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGeneratorsTest.kt
ExpList와 ExpList를 연결할 수 있도록 합니다
ex. `Person::dogs[0] into Dog::loves[0]`
=> Add ExpList into ExpList

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/FieldProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyDescriptorProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/RootProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/TypeReference.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorContextTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/generator/ArbitraryPropertyTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryTypeIntrospectDelegatorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryTypeIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaArbitraryTypeIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryTypeIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/matcher/ExactMatcherTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/property/FieldPropertyTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/property/PropertyCacheTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/property/PropertyDescriptorPropertyTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/property/RootPropertyTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/type/TypeReferenceTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/type/TypesTest.java, fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyJacksonArbitraryGeneratorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationArbitraryIntrospectorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationBooleanIntrospectorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationConstraintGeneratorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationTimeArbitraryIntrospectorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationTimeConstraintGeneratorTest.java
- Type 을 AnnotatedType 기준으로 관리하도록 변경합니다.
- AnnotatedType 에서 Type 을 얻을 수 있습니다.
=> Refactor use AnnotatedType

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryPropertyGeneratorContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryTypeIntrospectDelegator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BooleanTypeIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/CompositeArbitraryTypeIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/EnumTypeIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaArbitraryTypeIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryTypeIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/UuidTypeIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/ExactTypeMatcher.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/Matcher.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/MatcherOperator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/Matchers.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryTypeIntrospectDelegatorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaArbitraryTypeIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryTypeIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/matcher/ExactMatcherTest.java
Matcher 를 Property 를 받아서 판단하도록 수정합니다.
=> Refactor Matcher with property

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/ExpressionSpec.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/SimpleManipulatorTest.java
`set(표현식, Object)`만 남기고 나머지는 다 제거합니다.
=> Remove all additional set

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryExpression.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryNode.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryTree.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryType.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ComplexManipulatorTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java
generic을 가진 타입을 입력받아 생성하고 제어할 수 있도록 합니다.
=> Add generate Generic type

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyBuilderExtensions.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyExtensions.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/customizer/ArbitaryCustomizersExtensions.kt, fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyBuilderExtensionsTest.kt
=> Add addCustomizer kotlin extension to FixtureMonkeyBuilder

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyExtensions.kt, fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyExtensionsTest.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryTraverser.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryType.java
Gson같이 Type을 입력받도록 수정할 필요 없이 reified 사용하면 코틀린 컴파일러에서 알아서 해주는군요;
=> Add allowing generic type generate for kotlin extension

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/traverser/ArbitraryNode.java
- 신규 ArbitraryNode 를 정의합니다.
- 추가적인 요소들은 진행하면서 추가하도록하겠습니다.
=> Introduce new ArbitraryNode

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/TypeReference.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/type/TypeReferenceTest.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ComplexManipulatorTest.java
TypeReference로 입력한 타입이 generic type이 아닐 경우 register을 적용합니다.
=> Apply register when not generic type

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/SingleValueArbitraryPropertyGenerator.java
하위 속성이 없는 마지막 레벨의 SIngle Value 에 해당하는 정의(ArbitraryProperty) 를 생성하는 Generator 를 추가합니다.
=> Introduce SingleValueArbitraryPropertyGenerator

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/traverser/ArbitraryNode.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/traverser/ArbitraryTraverser.java
- 신규 ArbitraryTraverser 를 추가합니다.
- 큰 얼개만 작성한 것으로
- 이후 작업을 진행하면서 메소드 시그니처나 구현이 계속 수정될 수 있습니다.
- 어느정도 방향성이 결정이 되면 테스트를 작성하겠습니다.
=> Introduce new ArbitraryTraverser

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryTree.java
=> Shuffle sample list

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryIntrospectDelegator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryTypeIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BooleanIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/CompositeArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/EnumIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/TimeArbitraryTypeIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/UuidIntrospector.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryIntrospectDelegatorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/CompositeArbitraryIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaArbitraryIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryIntrospectorTest.java, fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationArbitraryTypeIntrospector.java, fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationBooleanIntrospector.java, fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationTimeArbitraryTypeIntrospector.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationArbitraryIntrospectorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationTimeArbitraryTypeIntrospectorTest.java
ArbitraryIntrospector 와 AribtraryTypeIntrospector 의 이름을 서로 바꿉니다.
=> Fix ArbitraryIntrospector name

fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/FieldReflectionArbitraryIntrospectorTest.java
=> Fix test compile fail

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt
구현이 달라지지는 않았고 이후에도 달라지지 않을 예정이기 때문에 테스트는 새로 추가하지 않았습니다.
=> Add Exp Extension for auto import

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/OptionalIntrospector.java
테스트는 아래 PR 반영되면 활용해서 추가 PR 로 작성하겠습니다.
https://github.com/naver/fixture-monkey/pull/253
=> Introduce OptionalIntrospector

content/en/docs/v0.3.x/Third-party Modules/FixtureMonkeyMockito.md, content/kr/docs/v0.3.x/Third-party Modules/FixtureMonkeyMockito.md
=> Fix typo in FixtureMonkeyMockito.md

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/OptionalIntrospector.java
하위 Arbitrary 생성을 메소드로 제공하고 Function 은 숨깁니다.
=> Refactor ArbitraryGeneratorContext childrenArbitraries generate

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryValue.java
우선 기본 구조만 추가하고, 점차 필요한 메소드들을 늘려나가야합니다.
=> Introduce ArbitraryBuilder

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTraverser.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java
ArbitraryBuilder 단계에서 V04 동작을 간단히 돌려보기 위한 sample test 를 추가합니다.
이후에 FixtureMonkey 에 V04 동작이 adapting 되면 FixtureMonkey 기준으로 테스트를 작성하고 이 테스트는 제거될 예정입니다.
(임시 테스트 코드 입니다.)
=> Add v04 sample test

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/RootNodeResolver.java
RootNode를 반환하는 Resolver를 추가합니다.
=> Add RootNodeResolver

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetDecomposedValueManipulator.java
값을 분해해서 Set하는 `NodeSetDecomposedValueManipulator` 를 추가합니다.
=> Add NodeSetDecomposedValueManipulator

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTraverser.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
부분적으로 traverse할 수 있도록 traverse 메소드 시그니쳐를 수정합니다.
=> Enable sub-traverse

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryContainerInfo.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryPropertyGeneratorContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ContainerArbitraryPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/EntryArbitraryPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/MapArbitraryPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/StreamArbitraryPropertyGenerator.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/generator/DefaultArbitraryGeneratorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/generator/DefaultNullInjectGeneratorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/BeanArbitraryIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/FieldReflectionArbitraryIntrospectorTest.java, fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/introspector/JacksonArbitraryIntrospectorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/generator/JavaxValidationArbitraryContainerInfoGeneratorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/generator/JavaxValidationNullInjectGeneratorTest.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryExpression.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryNode.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTraverser.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSizeManipulator.java
=> Add NodeSizeManipulator

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultNullInjectGenerator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetArbitraryManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetDecomposedValueManipulator.java
=> Remove null inject when set

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ContainerArbitraryPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/EntryArbitraryPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/MapArbitraryPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/OptionalArbitraryPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/PropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/StreamArbitraryPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ElementProperty.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/generator/KotlinPropertyGenerator.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/type/KotlinTypes.kt
iterable을 구현한 클래스들을 decompose 할 수 있게 ElementProperty#getValue를 구현합니다.
=> Add decompose iterable value

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/CompositeNodeManipulator.java
복수 개의 NodeManipulator를 포함하는 `CompositeNodeManipulator`를 추가합니다.
=> Add CompositeNodeManipulator

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeNullityManipulator.java
setNull, setNotNull에서 사용하는 manipulator를 추가합니다.
=> Add NodeNullityManipulator

content/en/docs/v0.3.x/Examples/Manipulator/ExpressionSpec.md, content/en/docs/v0.3.x/Examples/Manipulator/SimpleManipulator.md, content/en/docs/v0.3.x/Features/Manipulator.md, content/kr/docs/v0.3.x/Examples/Manipulator/ExpressionSpec.md, content/kr/docs/v0.3.x/Examples/Manipulator/SimpleManipulator.md, content/kr/docs/v0.3.x/Features/Manipulator.md
**Manipulator(연산) 부분 문서를 업데이트합니다.**
- Examples에서 발견한 오타 및 예제 오류 수정
- Manipulator 설명 추가
- 값으로 설정할 때와 Arbitrary로 설정할 때의 차이점 추가(Set by Value vs. Set by Arbitrary)
=> Update Manipulator doc

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
간단한 giveMeBuilder 동작이 가능하도록 구현합니다.
=> Add LabMonkey simple giveMeBuilder

content/en/docs/v0.3.x/Examples/Manipulator/ComplexManipulator.md, content/en/docs/v0.3.x/Examples/Manipulator/ExpressionSpec.md, content/en/docs/v0.3.x/Examples/Manipulator/SimpleManipulator.md, content/en/docs/v0.3.x/Examples/_index.md, content/kr/docs/v0.3.x/Examples/Manipulator/ComplexManipulator.md, content/kr/docs/v0.3.x/Examples/Manipulator/ExpressionSpec.md, content/kr/docs/v0.3.x/Examples/Manipulator/SimpleManipulator.md, content/kr/docs/v0.3.x/Examples/_index.md
문서 Examples의 Manipulator 부분의 예제들을 수정하였습니다.
- getter를 사용해 필드에 접근하도록 수정
- 실패하는 예제들 수정
=> Fix doc manipulator examples 

README.md
Readme에 작성된 Fixture Monkey 버젼을 0.3.4로 업데이트합니다.
=> Update Readme for 0.3.4

CONTRIBUTING.md
=> Add build from source guide

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/MapEntryElementArbitraryPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapEntryElementIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/MapEntryElementProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/MapKeyElementProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/MapValueElementProperty.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetDecomposedValueManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetLazyManipulator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java
다음과 같은 Container를 decompose하여 set 합니다.
1. List
2. Set
3. Map
4. Map.Entry
5. Optional
6. OptionalInt
7. OptionalLong
8. OptionalDouble
다음 PR에서는 OptionalXXX.empty()를 set할 때를 처리할 예정입니다.
=> Add decompose container

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ElementProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/MapEntryElementProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/MapKeyElementProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/MapValueElementProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/Property.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/TupleLikeElementsProperty.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryExpression.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetLazyManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSizeManipulator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
=> Add apply, acceptIf

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/Constants.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryExpression.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitrarySet.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitrarySetArbitrary.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitrarySetPostCondition.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/DefaultIterableSpec.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ApplyNodeCountManipulator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
=> Add set limit

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultNullInjectGenerator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryNode.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeNullityManipulator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
setNull을 기존 구조와 다르게 객체 조합 과정에서 처리하지 않고 nullInject를 활용해 처리합니다.
=> Add setNull, setNotNull

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultNullInjectGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/MapKeyElementProperty.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
map을 생성할 때 key는 null이 되지 않도록 수정합니다
=> Fix map key not returns null

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/LazyAnnotatedType.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetLazyManipulator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
=> Refactor map lazily

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkey.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
LabMonkey에 고정된 값으로 ArbitraryBuilder을 생성하는 giveMeBuilder를 추가합니다.
=> Add LabMonkey giveMeBuilder with fixed value

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilders.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
=> Add zipWith

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryTree.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/OptionalArbitraryNodeGenerator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetDecomposedValueManipulator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ComplexManipulatorTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
setNull을 실행한 후 fixed를 했을 때 null이 되지 않고 필드만 null이 되는 문제를 해결합니다
=> Fix fixed ArbitraryBuilder not return null after setNull root

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptionsBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryExpression.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryExpressionFactory.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/expression/MonkeyExpression.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/expression/MonkeyExpressionFactory.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ManipulateOptions.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ManipulateOptionsBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
ArbitraryExpression에 대한 직접적인 의존성을 제거하고 인터페이스 MonkeyExpression을 의존하도록 수정합니다.
사용자는 커스텀한 표현식을 MonkeyExpression을 확장해서 만들 수 있습니다.
=> Add MonkeyExpression for scalability

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkey.java
`giveMe`, `giveMeOne`, `giveMeArbitrary`를 추가합니다.
옵션, ArbitraryCustomizer를 입력받는 API는 이후에 추가할 예정입니다.
=> Add LabMonkey giveMe, giveMeOne, giveMeArbitrary

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
defaultArbitraryPropertyGenerator를 변경하는 옵션을 입력받습니다.
옵션은 별도 테스트 파일에서 테스트하도록 수정합니다.
=> Add alter defaultArbitraryPropertyGenerator option

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryPropertyGeneratorContext.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
PropertyNameResolver와 관련있는 옵션들을 추가합니다.
=> Add PropertyNameResolver options

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
NullInjectGenerator 옵션들을 추가합니다.
=> Add NullInjectGenerator options

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptionsBuilder.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/generator/JavaxValidationArbitraryContainerInfoGeneratorTest.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
ContainerInfo를 변경하는 옵션들을 추가합니다
=> Add ContainerInfo options

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
ArbitraryValidator를 변경하는 옵션을 추가합니다.
=> Add alter ArbitraryValidator options

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
하위 호환을 위해서 defaultNotNull, nullableContainer 옵션을 추가합니다.
=> Add nullable option

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
기존 Fixture Monkey 0.3.0 에서 지원하던 `exceptGenerate... ` 옵션들을 추가합니다.
=> Add except generate options

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTree.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTreeMetadata.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ManipulateOptions.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ManipulateOptionsBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/MetadataCollector.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
기본적인 ArbitraryBuilder를 등록하는 register 옵션을 추가합니다.
=> Add register to defined default ArbitraryBuilder

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ChildArbitraryContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BeanArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/EntryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FieldReflectionArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ListIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapEntryElementIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/OptionalIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/QueueIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/SetIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/StreamIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/TupleLikeElementsIntrospector.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonArbitraryIntrospector.java
FixtureMonkey 0.3.0 의 FieldArbitraries와 비슷한 역할을 할 ChildArbitraryContext를 추가합니다.
ArbitraryCustomizer에서 사용할 예정입니다.
=> Add ChildArbitraryContext

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt
Exp에서 존재하는 버그를 수정합니다.
1. 리스트는 intoGetter를 사용할 수 없는 버그
2. record에서 변수명에 `get`, `is`가 들어갈 경우 변수명을 잘못 인식하는 버그
=> Fix exp bug

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt
=> Fix compatible between property and getter

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryExpression.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
`$[0]`와 같이 List의 element를 가르키는 표현식을 지원합니다
=> Add support Expression for referencing List element

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTree.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeNullityManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSizeManipulator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
size 연산이 이전 연산의 결과를 유지하도록 수정합니다
=> Refactor size manipulation not changing values

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
build로 생성한 Arbitrary는 ArbitraryBuilder 연산에 영향을 받지 않도록 수정합니다.
=> Fix manipulator would not work after build

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
apply 실행 후 sample 하면 항상 다른 값이 나오도록 수정합니다.
=> Fix applied ArbitraryBuilder sampling twice returns diff

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetDecomposedValueManipulator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java
primitive와 reference 타입 간 비교도 가능하도록 유틸리티 메소드를 추가합니다.
https://github.com/apache/commons-lang/blob/b0739b066af253fe6810fb050b915f8608a383e6/src/main/java/org/apache/commons/lang3/ClassUtils.java#L1303
=> Add isAssignable for type matching

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
register로 등록한 연산이 항상 최우선순위를 가지도록 수정합니다
=> Fix register manipulator to higher priority

.github/auto_assign.yml
=> Add auto-assign reviewer

README.md
FixtureMonkey Helper 플러그인에 대한 내용을 추가합니다.
=> Update readme plugins

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/customizer/ArbitraryCustomizer.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/customizer/FixtureCustomizer.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptionsBuilder.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorContextTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/generator/JavaDefaultArbitraryGeneratorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryIntrospectDelegatorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/BeanArbitraryIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/FieldReflectionArbitraryIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaArbitraryIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryIntrospectorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/matcher/AssignableMatcherTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/matcher/ExactMatcherTest.java, fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/introspector/JacksonArbitraryIntrospectorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationArbitraryIntrospectorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationBooleanIntrospectorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationConstraintGeneratorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationTimeConstraintGeneratorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationTimeJavaArbitraryResolverTest.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTree.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
FixtureCustomizer를 추가합니다.
LabMonkeyBuilder에서 옵션으로 입력받는 경우만 추가합니다.
다음 PR에서 giveMe 메소드에서 입력받도록 추가할 예정입니다.
=> Add FixtureCustomizer

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ElementProperty.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java
`int[]` 같은 Primitive array를 생성 못하는 문제를 해결합니다.
=> Fix generating primitive array

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/OldArbitraryBuilderImpl.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
0.4.0v에서 사용할 수 있는 setLazy() 메소드를 추가합니다.
=> Add set lazy for DefaultArbitraryBuilder

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArrayArbitraryPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ContainerArbitraryPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultNullInjectGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/OptionalArbitraryPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/PropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/StreamArbitraryPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ElementProperty.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/generator/DefaultNullInjectGeneratorTest.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/generator/JavaDefaultArbitraryGeneratorTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/generator/JavaxValidationNullInjectGeneratorTest.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/generator/KotlinPropertyGenerator.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
ElementProperty에 불필요한 nullInject 필드를 제거합니다.
Container의 Element로 null을 생성하는 문제를 해결합니다.
=> Fix generating nullable element

fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04ExpressionGeneratorTest.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ManipulateOptions.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ManipulateOptionsBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ExpressionGeneratorTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ExpressionGeneratorTestSpecs.java
0.4.0V에서 ExpressionGenerator로 표현식을 생성하여 연산을 적용할 수 있도록 메소드를 추가합니다.
=> Add methods using ExpressionGenerator for DefaultArbitraryBuilder

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkey.java
LabMonkey 생성자에서 manipulateOptionsBuilder를 설정하는 순서를 변경합니다.
=> Refactor manipulateOptionsBuilder set up order

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptionsBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
LabMonkeyBuilder에서 ArbitraryIntrospector를 설정할 수 있는 메소드들을 추가합니다.
=> Add methods to set ArbitraryIntrospector

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
LabMonkeyBuilder에서 plugin을 설정할 수 있는 메소드를 추가합니다.
=> Add plugin method for LabMonkeyBuilder

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
LabMonkeyBuilder에 objectIntrospector를 설정할 수 있는 메소드를 추가합니다.
=> Add objectIntrospector method

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryExpression.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpec.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ApplyStrictModeResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/CompositeNodeResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ContainerElementNodeResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/IdentityNodeResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeKeyValueResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeLastEntryResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeResolver.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/InnerSpecTest.java
불필요한 ArbitraryTree 노출을 제거하기 위해 NodeResolver 인터페이스를 변경합니다.
=> Refactor NodeResolver interface

fixture-monkey-api/build.gradle, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BuilderArbitraryIntrospector.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/BuilderArbitraryIntrospectorTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsAdditionalTestSpecs.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
Builder를 활용하여 Arbitrary를 생성하는 BuilderArbitraryIntrospector를 추가합니다.
=> Add BuilderArbitraryIntrospector

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ManipulateOptionsBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/MetadataCollector.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java
루트 노드와 하위 노드를 등록했을 때 적용되지 않는 문제를 해결합니다.
=> Fix register child element

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/collection/LruCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptionsBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTree.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/IdentityNodeResolver.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsAdditionalTestSpecs.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
unique 하게 생성할 Property를 입력하는 옵션을 추가합니다.
=> Add uniqueProperty option

fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonArbitraryIntrospector.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/plugin/JacksonPlugin.java
JacksonPlugin에서 ObjectMapper를 변경할 수 있게 수정합니다
=> Add JacksonPlugin alter ObjectMapper

fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyJacksonArbitraryGeneratorTest.java, fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04ExpressionGeneratorTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsAdditionalTestSpecs.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/InnerSpecTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/InnerSpecTestSpecs.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/SpecTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/SpecTestSpecs.java
=> Polish test

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
register로 등록한 연산 결과가 달라지도록 수정합니다.
=> Fix register object not fixed

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyCache.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java
=> Refactor not generating static field

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/collection/IteratorCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/collection/StreamCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BuilderArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/TypeCache.java, fixture-monkey/build.gradle, fixture-monkey/src/jmh/java/com/navercorp/fixturemonkey/BenchmarkTest.java, fixture-monkey/src/jmh/java/com/navercorp/fixturemonkey/BuilderOrderSheet.java, fixture-monkey/src/jmh/java/com/navercorp/fixturemonkey/OrderSheet.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/MonkeyContextBuilder.java
성능 측정을 위해 jmh를 사용합니다.
initialCapacity를 정의해 resize가 최대한 일어나지 않도록 설정합니다.
=> Add benchmark

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetDecomposedValueManipulator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
Container를 두 번 이상 set할 수 있게 수정합니다.
=> Fix set decomposed container twice

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetDecomposedValueManipulator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
빈 컨테이너를 decompose할 수 있게 수정합니다.
=> Fix set empty container

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/SetContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java, fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/generator/JavaxValidationArbitraryContainerInfoGenerator.java, fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/plugin/JavaxValidationPlugin.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsAdditionalTestSpecs.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java
Enum을 생성할 때 최대 크기를 Enum에 선언한 값 이하가 되도록 설정합니다.
JavaxValidationPlugin 적용 조건을 추가합니다.
=> Add javaxValidation apply enum size

fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonArbitraryIntrospector.java, fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
=> Add JsonFormat

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ChildArbitraryContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultObjectPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ObjectProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptionsBuilder.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyExtensions.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/KotlinPlugin.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/PrimaryConstructorArbitraryIntrospector.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/KotlinPropertyCache.kt, fixture-monkey-kotlin/src/test/java/com/navercorp/fixturemonkey/kotlin/spec/JavaObject.java, fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/test/PrimaryConstructorArbitraryIntrospectorTest.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java
=> Add kotlin module

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/CompositeProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyCache.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/property/PropertyCacheTest.java
FieldProperty가 우선순위를 가지도록 수정합니다.
=> Refactor CompositeProperty order

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpec.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryBuilderContext.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTraverser.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/BuilderManipulatorAdapter.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ContainerInfoManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetDecomposedValueManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/TraverseContext.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/SpecTest.java
`size` 연산을 처리하는 manipulator를 추가합니다.
=> Add ContainerInfoManipulator

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapIntrospector.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpec.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryBuilderContext.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeAllEntryPredicate.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetLazyManipulator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/InnerSpecTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/InnerSpecTestSpecs.java
InnerSpec에 key, value, entry 에 대한 set lazy 연산과 set all lazy 연산을 추가합니다.
(InnerSpec 리팩토링은 추후 다른 PR로 할 예정입니다)
=> Add InnerSpec set lazy & set all lazy

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java
=> Add more java default packages

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/MetadataCollector.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
=> Fix register manipulation order

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultNullInjectGenerator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java
nullableContainer가 동작하지 않는 문제를 해결합니다
=> Fix nullableContainer

fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java
Fixture Monkey에서 사용하는 테스트 객체에서 생성할 수 있는 기본 자바 객체를 전부 추가합니다.
=> Add better test fixture

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ConstructorPropertiesArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ConstructorProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/TypeCache.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonArbitraryIntrospector.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04ConstructorPropertiesTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04ConstructorPropertiesTestSpecs.java
생성자로 생성하는 ConstructorPropertiesArbitraryIntrospector를 추가합니다.
=> Add ConstructorPropertiesArbitraryIntrospector

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultObjectPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/FactoryPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FactoryMethodArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptionsBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/FactoryMethodProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyCache.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04FactoryMethodGenerateTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04FactoryMethodGenerateTestSpecs.java
=> Add FactoryMethodIntrospector

fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/generator/JsonNodeContainerPropertyGenerator.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JsonNodeIntrospector.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/plugin/JacksonPlugin.java, fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04JacksonTest.java
JacksonPlugin 에서 JsonNode 타입에 대한 기본 introspector 를 구현합니다.
=> Add default JsonNode type introspector for JacksonPlugin

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpec.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/BuilderManipulatorAdapter.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetDecomposedValueManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetLazyManipulator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
apply에서 생성한 객체는 size 연산과 상관없이 항상 set이 되도록 수정합니다.
=> Refactor set forced

.github/workflows/auto-assign-action.yml
문서 PR을 올리면 auto-assign과 태그를 추가하도록 수정합니다.
바로 머지하겠습니다.
의견 있으시면 남겨주세요.
=> Add doc github action

.github/workflows/deploy.yml, build.gradle
태그를 만들면 자동으로 배포가 되도록 깃헙 액션을 추가합니다.
=> Add publish automatically when tagging

.github/ISSUE_TEMPLATE/bug_report_issue_template.md, .github/ISSUE_TEMPLATE/feature_request_issue_template.md, .github/ISSUE_TEMPLATE/question_issue_template.md, .github/PULL_REQUEST_TEMPLATE.md
PR template이 적용이 안돼서 파일 위치를 수정합니다.
헤더 크기도 함께 수정합니다.
=> Fix github Issue & PR templates

.github/workflows/deploy.yml, build.gradle
태그를 생성하면 sonatype nexus에 배포하고 자동으로 close, release까지 해주는 플러그인을 추가합니다.
=> Add nexus plugin for automation

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryTraverser.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/DefaultContainerArbitraryNodeGenerator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/ArrayBuilder.java
Removed comments that break compilation on systems with Cp1252 encoding. 
Fixes #500
=> Removed comments that break compilation on systems with Cp1252 encoding

.github/workflows/deploy.yml
=> Add close milestone github action

.github/workflows/deploy.yml
=> Add new milestone when published

fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsAdditionalTestSpecs.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
Fix mistakes in setting the `DecomposableContainerValue` for related tests.
=> Fix decomposeNewContainer tests

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyCache.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/property/NotPropertyValue.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/property/PropertyCacheTest.java
Fix PropertyDescriptorProperty not generating only getter or setter
=> Fix PropertyDescriptorProperty not generating only getter or setter

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpec.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/InnerSpecTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/InnerSpecTestSpecs.java
Add missing innerSpec methods, such as `allListElement`, `allKey`, `allValue`
* InnerSpecTest
=> Add more innerSpec support methods

README.md
Added kotlin example code to README.md
=> Add kotlin example code to README.md

content/en/docs/v0.4/Release Notes/_index.md, content/kr/docs/v0.4/Release Notes/_index.md
=> Update 0.4.9 documentation

config.toml, content/en/docs/v0.4/Examples/JavaxValidation.md, content/en/docs/v0.4/Getting started/_index.md, content/en/docs/v0.4/Getting started/java.md, content/en/docs/v0.4/Getting started/kotlin.md, content/en/docs/v0.4/Getting started/lombok.md, content/en/docs/v0.4/Third-party Modules/fixture-monkey-autoparams.md, content/en/docs/v0.4/Third-party Modules/fixture-monkey-engine.md, content/en/docs/v0.4/Third-party Modules/fixture-monkey-jackson.md, content/en/docs/v0.4/Third-party Modules/fixture-monkey-javax-validation.md, content/en/docs/v0.4/Third-party Modules/fixture-monkey-junit-jupiter.md, content/en/docs/v0.4/Third-party Modules/fixture-monkey-kotlin.md, content/en/docs/v0.4/Third-party Modules/fixture-monkey-mockito.md, content/kr/docs/v0.4/Examples/JavaxValidation.md, content/kr/docs/v0.4/Getting started/_index.md, content/kr/docs/v0.4/Getting started/java.md, content/kr/docs/v0.4/Getting started/kotlin.md, content/kr/docs/v0.4/Getting started/lombok.md, content/kr/docs/v0.4/Third-party Modules/fixture-monkey-autoparams.md, content/kr/docs/v0.4/Third-party Modules/fixture-monkey-engine.md, content/kr/docs/v0.4/Third-party Modules/fixture-monkey-jackson.md, content/kr/docs/v0.4/Third-party Modules/fixture-monkey-javax-validation.md, content/kr/docs/v0.4/Third-party Modules/fixture-monkey-junit-jupiter.md, content/kr/docs/v0.4/Third-party Modules/fixture-monkey-kotlin.md, content/kr/docs/v0.4/Third-party Modules/fixture-monkey-mockito.md
=> Update version by variable

config.toml, content/en/docs/v0.4/Release Notes/_index.md, content/kr/docs/v0.4/Release Notes/_index.md
Update documentation for 0.4.10
=> Update 0.4.10 documentation

fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/type/TypesTest.java, fixture-monkey-autoparams/src/main/java/com/navercorp/fixturemonkey/autoparams/FixtureMonkeyAutoSource.java, fixture-monkey-engine/src/main/java/com/navercorp/fixturemonkey/engine/jupiter/extension/FixtureMonkeySessionExtension.java, fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/property/JacksonPropertyNameResolverTest.java, fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04ExpressionGeneratorTest.java, fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04JacksonTest.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyBuilderExtensions.kt, fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyV04JavaTest.kt, fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/test/PrimaryConstructorArbitraryGeneratorTestSpecs.kt, fixture-monkey-starter/src/test/java/com/navercorp/fixturemonkey/starter/FixtureMonkeyStarterTest.java
Add missing license infos
Local build.
=> Add missing license infos

config.toml, content/en/docs/v0.4/Release Notes/_index.md, content/kr/docs/v0.4/Release Notes/_index.md
=> Update 0.4.11 documentation

content/en/docs/v0.4/Third-party Modules/fixture-monkey-jakarta-validation.md, content/kr/docs/v0.4/Third-party Modules/fixture-monkey-jakarta-validation.md
jakarta-validation 모듈에 대한 doc 추가합니다.
혹시 weight 조정 필요하면 코멘트 주세요 :) (화면에 나오는 순서인 것 같은데, 우선 가장 큰 값으로 넣었습니다)
=> Add jakarta-validation doc

fixture-monkey-autoparams/src/test/java/com/navercorp/fixturemonkey/autoparams/test/FixtureMonkeyValueCustomizerTest.java, fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyJacksonArbitraryGeneratorTest.java, fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyBuilderExtensionsTest.kt, fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyExtensionsTest.kt, fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/KotlinNullableArbitraryEvaluatorTest.kt, fixture-monkey-mockito/src/test/java/com/navercorp/fixturemonkey/mockito/test/FixtureMonkeyMockitoInterfaceSupplierTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ArbitraryCustomizerTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ArbitraryGeneratorTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ComplexManipulatorTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/SimpleManipulatorTest.java
=> Add @Deprecate for 0.3 tests

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java
Supports complex generic types
Check out tests
Adding type interface for Fixture Monkey and polishing `Types` code would be next PRs
resolves #546
* sampleGeneric
* sampleGenericWildcardExtends
* sampleStringGenericField
* sampleGenericField
* sampleGenericChild
* sampleTwoGenericChild
* sampleObjectField
* sampleChildValue
=> Add supporting complex generic types

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
Fix generating type with wildcard
* sampleWildcard
=> Fix generating type with wildcard

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryExpression.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpec.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTraverser.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/IdentityNodeResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/RootNodePredicate.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/TraverseContext.java
Refactor rootNode matching logic
Unifying ContainerInfoManipulator matching logic
=> Refactor rootNode matching logic

config.toml, content/en/docs/v0.4/Release Notes/_index.md, content/kr/docs/v0.4/Release Notes/_index.md
=> Update 0.4.12 documentation

content/en/docs/v0.4/Examples/MapSet.md, content/en/docs/v0.4/Examples/NestedMapSet.md, content/kr/docs/v0.4/Examples/MapSet.md, content/kr/docs/v0.4/Examples/NestedMapSet.md
Update InnerSpec examples in document
=> Update InnerSpec documentation

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryExpression.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpec.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/IdentityNodeResolver.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/InnerSpecTest.java
Fix size root with InnerSpec
0.5부터는 이슈 없습니다.
0.4는 간단하게만 수정합니다.
* InnerSpecTest#size
=> Fix size root with InnerSpec

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java
Fix generating AnnotatedWildcard type
* sampleMapValueWildcardListString
=> Fix generating AnnotatedWildcard type

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTestSpecs.java
Fix generating fields in child class with generic
resolves #570 
* sampleGenericSimpleObject
=> Fix generating fields in child class with generic

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ContainerInfoManipulator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java
Fix registered size
* registerFieldSize
=> Fix registered size

content/en/docs/v0.4/Release Notes/_index.md, content/kr/docs/v0.4/Release Notes/_index.md
=> Update 0.4.14 documentation 

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryContainerInfo.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/EntryContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/MapContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/MapEntryElementContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/OptionalContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/SetContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/TupleLikeElementsPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptionsBuilder.java, fixture-monkey-jakarta-validation/src/main/java/com/navercorp/fixturemonkey/jakarta/validation/generator/JakartaValidationArbitraryContainerInfoGenerator.java, fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/generator/JavaxValidationArbitraryContainerInfoGenerator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpec.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpecState.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/ManipulatorSet.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/MonkeyManipulatorFactory.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryBuilderContext.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ContainerInfoManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetDecomposedValueManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetLazyManipulator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsAdditionalTestSpecs.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/InnerSpecTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/InnerSpecTestSpecs.java
Refactor executing a manipulator in order
* sizeAfterSetReturnsSet
* sizeAfterSetEmptyListReturnsSized
* greaterSizeAfterSetReturnsSizeRemainsSet
* smallerSizeAfterSetReturnsSizeRemainsSet
* setAfterSizeReturnsSet
* sizeAfterSetReturnsSize
* sizeAfterSetWithSeparateInnerSpecReturnsSize
* setAfterSetWithSeparateInnerSpecReturnsSet
* innerSpecIncrementsSequence
=> Refactor executing a manipulator in order

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/MonkeyManipulatorFactory.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/InnerSpecTest.java
Add notNull in the set manipulation
* setNotNull
=> Add notNull in the set manipulation

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/MonkeyManipulatorFactory.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java
Fix size nested element not working when registered
* sizeElementWhenRegisteredSize
=> Fix size nested element not working when registered

README.md
Update readme example for 0.5.0
Local test
=> Update readme example code

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/MonkeyManipulatorFactory.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/Values.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetJustManipulator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/InnerSpecTest.java
Add just for set an instance of value
* setJust
* setJustSubPropertyNotChanged
=> Add just for setting an instance of value

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyCache.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyConstructorPropertiesTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyConstructorPropertiesTestSpecs.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java
Fix ConstructorProperty has a generic type
* FixtureMonkeyTest#sampleGeneric
* FixtureMonkeyTest#sampleGenericWildcardExtends
* FixtureMonkeyConstructorPropertiesTest#sampleGeneric
* FixtureMonkeyConstructorPropertiesTest#sampleFixedGeneric
=> Fix ConstructorProperty has a generic type

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeFilterManipulator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java
Fix set primitive type postCondition
* setPostConditionPrimitiveType
=> Fix set primitive type postCondition

fixture-monkey-tests/build.gradle, fixture-monkey-tests/java-17-tests/build.gradle, fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/ConstructorPropertiesRecordTest.java, fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/JacksonRecordTest.java, fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/RecordTestSpecs.java, fixture-monkey-tests/kotlin-tests/build.gradle, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/SealedClassTest.kt, fixture-monkey-tests/src/main/java/com/navercorp/fixturemonkey/tests/TestEnvironment.java, settings.gradle
Add test modules
Existing tests would be moved in next PR
=> Add test modules

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultArbitraryBuilder.java
Add comments for methods in ArbitraryBuilder
=> Add comments for methods in ArbitraryBuilder

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryNode.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTraverser.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTree.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetDecomposedValueManipulator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyConstructorPropertiesTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyConstructorPropertiesTestSpecs.java
Refactor interface applies the implementation option
* interfaceAppliesImplementationOption
=> Refactor interface applies the implementation option

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java, fixture-monkey-tests/java-tests/build.gradle, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/ImmutableGenericTypeSpecs.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/ImmutableJavaTestSpecs.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/ImmutableRecursiveTypeSpecs.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey-tests/java-tests/src/test/lombok.config, settings.gradle
Add Java test module for migration
=> Add Java test module for migration

README.md
Update README thumbnail
check out new README thumbnail in [here](https://github.com/naver/fixture-monkey/tree/sa/update-thumnbail)
=> Update README thumbnail

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/KotlinPlugin.kt, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/SealedClassTest.kt
Add sampling sealed class
* tests in SealedClassTest
=> Add sampling sealed class

.github/workflows/build.yml, fixture-monkey-jakarta-validation/build.gradle, fixture-monkey-javax-validation/build.gradle, fixture-monkey/build.gradle
=> Add retry plugin

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/PropertyGenerator.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/generator/KotlinPropertyGenerator.kt
Remove unused property generate methods in PropertyGenerator
=> Remove unused property generate methods in PropertyGenerator

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ManipulateOptionsBuilder.java
Remove monkeyExpressionFactory option
=> Remove monkeyExpressionFactory option

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/MonkeyManipulatorFactory.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeSetDecomposedValueManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeSetLazyManipulator.java
Remove direct dependency with ManipulateOptions
=> Remove direct dependency with ManipulateOptions

content/en/docs/v0.5/Release Notes/_index.md, content/kr/docs/v0.5/Release Notes/_index.md
=> Update 0.5.3 documentation

.github/workflows/build.yml
=> Fix run test retry

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/JavaDefaultArbitraryGeneratorBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapEntryIntrospector.java
Deprecate EntryIntrospector
Deprecate EntryIntrospector, Add MapEntryIntrospector
=> Deprecate EntryIntrospector

fixture-monkey-jakarta-validation/build.gradle, fixture-monkey-jakarta-validation/src/main/java/com/navercorp/fixturemonkey/jakarta/validation/plugin/JakartaValidationPlugin.java, fixture-monkey-jakarta-validation/src/main/java/com/navercorp/fixturemonkey/jakarta/validation/validator/JakartaArbitraryValidator.java, fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/plugin/JavaxValidationPlugin.java, fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/validator/JavaxArbitraryValidator.java, fixture-monkey/build.gradle, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryValue.java
Split DefaultArbitraryValidator into Javax and Jakarta Validator
It would be working when adds fixture-monkey-jakarta-validation module.
=> Split DefaultArbitraryValidator into Javax and Jakarta Validator

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java
Remove warning when import TypeVariableImpl
=> Remove warning when import TypeVariableImpl

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpec.java
Adds Javadoc for `InnerSpec` public methods
No tests needed.
=> Add InnerSpec Javadoc

fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonObjectArbitraryIntrospector.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/plugin/JacksonPlugin.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JacksonTest.java
Add supporting @JsonSubTypes and @JsonTypeInfo
* jsonTypeInfoName
* jsonTypeInfoList
* jsonTypeInfoIdClass
* jsonTypeWithAnnotations
* jsonTypeWithAnnotationsList
* jsonTypeInfoListInSetter
* jsonTypeInfoListIncludeWrapperObject
* jsonTypeInfoListInSetterIncludeWrapperObject
* jsonTypeWithAnnotationsIncludeWrapperObjectList
=> Add supporting @JsonSubTypes and @JsonTypeInfo

.github/workflows/benchmark.yml, .github/workflows/build.yml, fixture-monkey/src/jmh/java/com/navercorp/fixturemonkey/ManipulationBenchmark.java, fixture-monkey/src/jmh/java/com/navercorp/fixturemonkey/ObjectGenerationBenchmark.java
*Describe what feature is implemented by this PR.*
*If there is a related issue, write the issue number and link*
=> Add manipulation benchmark

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/MonkeyManipulatorFactory.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectNode.java
Add ObjectNode a parent reference
=> Add ObjectNode a parent reference

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArrayIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ListIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapEntryElementIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/QueueIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/SetIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/StreamIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/TupleLikeElementsIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/DoubleGenericTypeMatcher.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/SingleGenericTypeMatcher.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JsonNodeIntrospector.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/ImmutableJavaTestSpecs.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTestSpecs.java
Remove generating the type implements containerType without generic
* sampleSetImplementationWithoutGeneric
* fixedSetImplementationWithoutGeneric
=> Remove generating the type implements containerType without generic

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyCache.java
Add generating inaccessible field type as null, printing warning
=> Add generating inaccessible field type as null, printing warning

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArrayIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/FieldPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/type/TypesTest.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/ImmutableGenericTypeSpecs.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java
Add supporting GenericArray type
=> Add supporting GenericArray type

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/customizer/FixtureCustomizer.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptionsBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java
=> Polish FixtureCustomizer

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/KotlinPropertyGenerator.kt
Refactor kotlinPropertyGenerator for using delegate PropertyGenerator
=> Refactor KotlinPropertyGenerator for using delegate PropertyGenerator

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java
Fix generic type to match by type name
=> Fix generic type to match by type name

.editorconfig
Fix multiple catch indentation issue.
resolves issue mentions [here](https://github.com/naver/fixture-monkey/pull/508#discussion_r1036875227)
=> Fix multiple catch indentation issue

content/en/docs/v0.5/Examples/Register.md, content/kr/docs/v0.5/Examples/Register.md
=> Add missing return keyword

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/collection/IteratorCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/collection/StreamCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyContextBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BuilderArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/TypeCache.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/PrimaryConstructorArbitraryIntrospector.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/KotlinPropertyCache.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/KotlinPropertyGenerator.kt
=> Deprecate PropertyCache

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java
Fix Jqwik memoization equals bug
=> Fix Jqwik memoization equals bug

README.md
Add my name to the contribute page as an intern.
=> Add contribute

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FailoverIntrospector.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/ImmutableMixedIntrospectorsTypeSpecs.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/NoArgsConstructorJavaTestSpecs.java
Add FailoverIntrospector
FailoverIntrospector would continue to introspect even if the one of introspector is failed.
* failoverIntrospector
* failoverIntrospectorMixed
=> Add FailoverIntrospector

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java
Remove redundant ArbitraryGeneratorContext generation
=> Remove redundant ArbitraryGeneratorContext generation

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/MonkeyStringArbitrary.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java
Make MonkeyStringArbitrary class
Check if the sample value is not null. See `sampleWithMonkeyStringArbitrary()`
=> Write MonkeyStringArbitrary class, override basic methods

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/FilteredCombinableArbitrary.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/TraceableCombinableArbitrary.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyGeneratorContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/exception/FilterMissException.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultArbitraryGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapEntryElementIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapEntryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/SetIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyPath.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/Traceable.java, fixture-monkey-jakarta-validation/src/main/java/com/navercorp/fixturemonkey/jakarta/validation/validator/JakartaArbitraryValidator.java, fixture-monkey-jakarta-validation/src/test/java/com/navercorp/fixturemonkey/jakarta/validation/JakartaValidationFixtureMonkeyTest.java, fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/validator/JavaxArbitraryValidator.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/JavaxValidationFixtureMonkeyTest.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java
Add logging when filter is failed
https://github.com/naver/fixture-monkey/issues/490
* logRoot
* logProperty
* logArrayElement
* logListElementProperty
* logMapElementKeyProperty
* logMapElementValueProperty
* logFailedProperties
=> Add logging when filter is failed

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/collection/IteratorCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/container/IteratorCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/container/LruCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/container/StreamCache.java
Move collection package into container
=> Refactor moving collection package into container

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/container/DecomposableJavaContainer.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/container/DecomposedContainerValueFactory.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/container/DefaultDecomposedContainerValueFactory.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptionsBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/MonkeyManipulatorFactory.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeSetDecomposedValueManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeSetLazyManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DecomposedContainerValueFactory.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultDecomposedContainerValueFactory.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ManipulateOptions.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ManipulateOptionsBuilder.java
Refactor move DecomposedContainerValueFactory into api module
=> Refactor move DecomposedContainerValueFactory into api module

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ManipulateOptions.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ManipulateOptionsBuilder.java
Refactor moving register from ManipulateOptions to FixtureMonkey
=> Refactor moving register from ManipulateOptions to FixtureMonkey

fixture-monkey-starter/build.gradle
Add fixture-monkey-jakarta-validation dependency in starter module
=> Add fixture-monkey-jakarta-validation dependency in starter module

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArrayContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ContainerPropertyGeneratorContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultObjectPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultSingleContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/InterfaceObjectPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/MapContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ObjectPropertyGeneratorContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/SetContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/SingleValueObjectPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/StreamContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptions.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/plugin/Plugin.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/generator/ElementJsonSubTypesObjectPropertyGenerator.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/generator/JsonNodeContainerPropertyGenerator.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/generator/PropertyJsonSubTypesObjectPropertyGenerator.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/plugin/JacksonPlugin.java, fixture-monkey-jakarta-validation/src/main/java/com/navercorp/fixturemonkey/jakarta/validation/generator/JakartaValidationArbitraryContainerInfoGenerator.java, fixture-monkey-jakarta-validation/src/main/java/com/navercorp/fixturemonkey/jakarta/validation/plugin/JakartaValidationPlugin.java, fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/generator/JavaxValidationArbitraryContainerInfoGenerator.java, fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/plugin/JavaxValidationPlugin.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/KotlinPlugin.kt, fixture-monkey-mockito/src/main/java/com/navercorp/fixturemonkey/mockito/plugin/MockitoPlugin.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ArbitraryTraverser.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java
Refactor FixtureMonkeyOptions replaces GenerateOptions
=> Refactor FixtureMonkeyOptions replaces GenerateOptions

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/container/ConcurrentLruCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/container/IteratorCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/container/StreamCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyContextBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryIntrospectorResult.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/TypeCache.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/PrimaryConstructorArbitraryIntrospector.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/KotlinPropertyCache.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/KotlinPropertyGenerator.kt, fixture-monkey-tests/java-concurrent-tests/build.gradle, fixture-monkey-tests/java-concurrent-tests/src/test/java/com/navercorp/fixturemonkey/tests/concurrent/ConcurrentTest.java, fixture-monkey-tests/java-concurrent-tests/src/test/resources/junit-platform.properties, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java, settings.gradle
* Fix generated concurrently
* tests in `java-concurrent-tests`
=> Fix generated concurrently

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/CombinableArbitrary.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/ContainerCombineArbitraryBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyContextBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapEntryElementIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/SetIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptions.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java
Add options for generation count
=> Add options for generation count

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryContainerInfo.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultNullInjectGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArrayIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ListIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapEntryElementIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapEntryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/OptionalIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/QueueIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/SetIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/StreamIntrospector.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JsonNodeIntrospector.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/PairIntrospector.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/TripleIntrospector.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/ContainerInfoManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/MonkeyManipulatorFactory.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeSetDecomposedValueManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ArbitraryTraverser.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectNode.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsAdditionalTestSpecs.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java
Remove ContainerProperty in ArbitraryNode
=> Remove ContainerProperty in ArbitraryNode

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/CombinableArbitrary.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/AnonymousArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryIntrospectorResult.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeNullityManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java
Add split factory method for type Inference
=> Add split factory method

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/CombinableArbitrary.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/JavaTimeArbitraryGeneratorSet.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/JavaTypeArbitraryGeneratorSet.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/JavaDefaultArbitraryGeneratorBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/jqwik/JqwikJavaTimeArbitraryGeneratorSet.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/jqwik/JqwikJavaTypeArbitraryGeneratorSet.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java
Refactor deducting dependency with jqwik
=> Refactor deducting dependency with jqwik

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultArbitraryBuilder.java
=> Rename apply to thenApply

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/JavaTimeArbitraryGeneratorSet.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryResolver.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeTypeArbitraryGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/jqwik/JqwikJavaTimeArbitraryGeneratorSet.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTestSpecs.java
`ZoneId`을 추가합니다.
`SimpleObject`에 타입 추가하여 `setNotNullZoneId` 테스트 추가합니다.
=> Add ZoneId introspector

settings.gradle
=> Polish settings.gradle

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/CompositeArbitraryGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultArbitraryGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/IteratorIntrospector.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultArbitraryBuilder.java
Remove raw type CombinableArbitrary
=> Remove raw type CombinableArbitrary

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FieldReflectionArbitraryIntrospector.java
Fix set final fields, omit only static final fields
=> Fix set final fields

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/KotlinPropertyGenerator.kt, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/CircularReferenceTest.kt, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/GenericTest.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ArbitraryTraverser.java
Fix bugs in Kotlin
There are two bugs in Kotlin.
1. Type has a self-reference without nullable
2. Type has a property with generic
* CircularReferenceTest
* GenericTest
=> Fix bugs in Kotlin

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ArbitraryBuilderExtensions.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyBuilderExtensions.kt
=> Add kotlin extensions

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyBuilderExtensions.kt
Add extensions for kotlin (List of KClass).
---
이야기 했어서 한번 더 봐봤네요.
=> Enhance kotlin extensions

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/ContainerCombinableArbitrary.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/ObjectCombinableArbitrary.java
Refactor CombinableArbitrary clears only if fixed
=> Refactor CombinableArbitrary clears only if fixed

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/container/DefaultDecomposedContainerValueFactory.java
Add MapEntryElementType in DefaultDecomposedContainerValueFactory
=> Add MapEntryElementType in DefaultDecomposedContainerValueFactory

.github/workflows/build.yml
Split build and test for better measurement
=> Split build and test for better measurement

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapEntryElementIntrospector.java
=> Fix generating unique key

.github/workflows/github-page.yml, layouts/partials/head/script-header.html
=> Add Google Analytics to Doc v2

config/_default/config.toml, config/production/config.toml
=> Fix Doc Ver 2 config

assets/js/index.js, content/en/docs/fixture-monkey-options/customization-options.md, layouts/partials/header/header.html, layouts/partials/main/docs-navigation.html
Fix link errors & modify flexSearch
=> Fix link errors & modify flexSearch

.github/workflows/build.yml, gradle.properties
=> Add gradle caching

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/CombinableArbitrary.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/FilteredCombinableArbitrary.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/constraint/JavaConstraintGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyContextBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/exception/ContainerSizeFilterMissException.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/exception/FixedValueFilterMissException.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/exception/RetryableFilterMissException.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ValidateArbitraryGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapEntryElementIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/jqwik/JqwikJavaArbitraryResolver.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/jqwik/JqwikJavaTimeArbitraryResolver.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java, fixture-monkey-jakarta-validation/src/main/java/com/navercorp/fixturemonkey/jakarta/validation/introspector/JakartaValidationConstraintGenerator.java, fixture-monkey-jakarta-validation/src/test/java/com/navercorp/fixturemonkey/jakarta/validation/JakartaValidationFixtureMonkeyTest.java, fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationConstraintGenerator.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/JavaxValidationFixtureMonkeyTest.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ResolvedCombinableArbitrary.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectNode.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java
Add ValidateArbitraryGenerator
=> Add ValidateArbitraryGenerator

fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/ValueClassTest.kt
Add a test generating Kotlin Value Class
* ValueClassTest#foo
=> Add a test generating Kotlin Value Class

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ArbitraryTraverser.java
Refactor ArbitraryTraverser for separation of concerns
=> Refactor ArbitraryTraverser for separation of concerns

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/constraint/JavaDateTimeConstraint.java, fixture-monkey-jakarta-validation/src/main/java/com/navercorp/fixturemonkey/jakarta/validation/introspector/JakartaValidationConstraintGenerator.java, fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationConstraintGenerator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectNode.java
Add making time annotation cacheable
=> Add making time annotation cacheable

.github/workflows/benchmark.yml, fixture-monkey/build.gradle
=> Add benchmark summary

.github/workflows/build.yml, .github/workflows/test-report.yml
=> Upgrade test summary

fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/ImmutableRecursiveTypeSpecs.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ArbitraryTraverser.java
Fix generating self reference map type with diff key type
* sampleSelfRecursiveMapObject
* fixedSelfRecursiveMapObject
=> Fix generating self reference map type with diff key type

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/MonkeyManipulatorFactory.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeSetDecomposedValueManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/DefaultNodeResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/IdentityNodeResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectNode.java
Remove setManipulated explicitly
=> Remove setManipulated explicitly

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/CombinableArbitrary.java
Refactor CombinableArbitrary factory method using type inference
=> Refactor CombinableArbitrary factory method using type inference

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/AnonymousArbitraryIntrospector.java, fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/test/PrimaryConstructorArbitraryIntrospectorTest.kt, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/AnonymousInstanceTest.java
Fix sampleList always return same element with AnonymousArbitraryIntrospector
* sampleListWouldReturnDiff
=> Fix sampleList always returns same element with AnonymousArbitraryIntrospector

build.gradle, fixture-monkey-api/build.gradle, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/AnonymousArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/InvocationHandlerBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/AnnotatedTypes.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java, fixture-monkey-api/src/main/java17/com/navercorp/fixturemonkey/api/introspector/InvocationHandlerBuilder.java, fixture-monkey-api/src/main/java17/com/navercorp/fixturemonkey/api/type/AnnotatedTypes.java, fixture-monkey-junit-jupiter/build.gradle, fixture-monkey-kotlin/build.gradle, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/type/KotlinTypes.kt, fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/InterfaceDefaultMethodTest.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/AnonymousInstanceTest.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/AnonymousInstanceTestSpecs.java, fixture-monkey-tests/kotlin-concurrent-tests/build.gradle, fixture-monkey-tests/kotlin-tests/build.gradle, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java
Add multi-release Jar for `fixture-monkey-api`
=> Add multi-release Jar

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultArbitraryBuilder.java
Refactor ArbitraryResolver depending on ArbitraryBuilderContext
It is not exposed API, so no breaking change.
=> Refactor ArbitraryResolver depending on ArbitraryBuilderContext

fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/TraverseContext.java
Fix setting a nested self reference object
=> Fix setting a nested self reference object

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/random/Randoms.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java
Add seed for deterministic re-runs
=> Add seed for deterministic re-runs

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertySelector.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultArbitraryBuilder.java
Add PropertySelector interface
Remove direct dependency with `ExpressionGenerator`
=> Add PropertySelector interface

build.gradle, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java, fixture-monkey-kotest/build.gradle, fixture-monkey-kotest/gradle.properties, fixture-monkey-kotest/src/main/kotlin/com/navercorp/fixturemonkey/kotest/ArbExtension.kt, fixture-monkey-kotest/src/main/kotlin/com/navercorp/fixturemonkey/kotest/CheckAllExtension.kt, fixture-monkey-kotest/src/main/kotlin/com/navercorp/fixturemonkey/kotest/ForAllExtension.kt, fixture-monkey-kotest/src/main/kotlin/com/navercorp/fixturemonkey/kotest/KotestArbitraryGeneratorSet.kt, fixture-monkey-kotest/src/main/kotlin/com/navercorp/fixturemonkey/kotest/KotestPlugin.kt, fixture-monkey-tests/kotlin-tests/build.gradle, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotestInJunitTest.kt, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotestInKotestTest.kt, settings.gradle
=> Add supporting kotest module

fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeSetDecomposedValueManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ArbitraryTraverser.java
Fix size nested map within thenApply
* thenApplyAndSizeMap
=> Fix size nested map within thenApply

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/FilteredCombinableArbitrary.java, fixture-monkey-jakarta-validation/src/test/java/com/navercorp/fixturemonkey/jakarta/validation/JakartaValidationFixtureMonkeyTest.java, fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/JavaxValidationFixtureMonkeyTest.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/AnnotationTest.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/ValidationAnnotationTestSpecs.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ResolvedCombinableArbitrary.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java
Add validating a custom validation annotation
* AnnotationTest#sampleCustomAnnotation
=> Add validating a custom validation annotation

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BooleanIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/EnumIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/OptionalIntrospector.java, fixture-monkey-kotlin/build.gradle, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/generator/InterfaceKFunctionPropertyGenerator.kt, fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/test/KotlinExpJacksonPropertyTest.kt
Remove direct dependency with Jqwik Arbitrary
=> Remove direct dependency with Jqwik Arbitrary

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsAdditionalTestSpecs.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java
* Fix decomposing interface object
* decomposeNewContainerByAddContainerTypeInterface
=> Fix decomposing interface object

fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeSetLazyManipulator.java
Fix setLazy returning Just
* setLazyJust
=> Fix setLazy returning Just

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/CombinableArbitraryDelegator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/JavaDefaultArbitraryGeneratorBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/MatchArbitraryGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BeanArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/CompositeArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FieldReflectionArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MatchArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/MatchArbitraryIntrospectorTest.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/plugin/JacksonPlugin.java, fixture-monkey-jakarta-validation/src/main/java/com/navercorp/fixturemonkey/jakarta/validation/plugin/JakartaValidationPlugin.java, fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/plugin/JavaxValidationPlugin.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/KotlinPlugin.kt, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/ConstructorAndPropertyTestSpecs.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java
Add support for generation with mixed 2 or more introspectors
* compositeArbitraryGenerator
=> Add support for generation with mixed 2 or more introspectors

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArrayContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ContainerPropertyGeneratorContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultSingleContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/EntryContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/MapContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/SetContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/StreamContainerPropertyGenerator.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/generator/JsonNodeContainerPropertyGenerator.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java
Refactor ContainerPropertyGeneratorContext removing Options
=> Refactor ContainerPropertyGeneratorContext removing Options

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultObjectPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/InterfaceObjectPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ObjectPropertyGeneratorContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/SingleValueObjectPropertyGenerator.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/generator/ElementJsonSubTypesObjectPropertyGenerator.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/generator/PropertyJsonSubTypesObjectPropertyGenerator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/experimental/InstantiatorProcessor.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryBuilderContext.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ArbitraryTraverser.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/TraverseContext.java
Refactor ObjectPropertyGeneratorContext removing Options
=> Refactor ObjectPropertyGeneratorContext removing Options

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/FactoryMethodInstantiator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/FactoryMethodInstantiatorJava.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/Instantiator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/JavaInstantiatorProcessor.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FactoryMethodArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/MethodParameterProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/experimental/KotlinInstantiator.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/experimental/KotlinInstantiatorDsl.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/CompanionObjectFactoryMethodIntrospector.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/type/KotlinTypes.kt, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/ConstructorTestSpecs.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/InstantiatorTest.kt
Add factory method Instantiate DSL
It is a next PR of https://github.com/naver/fixture-monkey/pull/799
* instantiateByFactoryMethod
* instantiateByMixedTwoTypes
* instantiateByCompanionObjectFactoryMethod
* setInstantiateByCompanionObjectFactoryMethod
=> Add factory method Instantiate DSL

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ArbitraryBuilderExtensions.kt, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotestInJunitTest.kt
Fix Kotlin setPostCondition extension
* setPostConditionExtension
=> Fix Kotlin setPostCondition extension

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/Instantiator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/JavaInstantiatorProcessor.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/JavaPropertyInstantiator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/PropertyInstantiator.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/experimental/KotlinInstantiator.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/experimental/KotlinInstantiatorDsl.kt, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/InstantiatorTest.kt
Add PropertyInstantiator
* instantiateProperty
* instantiateJavaObjectByProperty
=> Add PropertyInstantiator

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/experimental/KotlinInstantiatorDsl.kt, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/InstantiatorTest.kt
Add Kotlin NoArgsConstructor extension
* instantiateNoArgsConstructor
* instantiatePropertyNoArgsConstructor
=> Add Kotlin NoArgsConstructor extension

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/ConstructorInstantiator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/FactoryMethodInstantiator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/FactoryMethodInstantiatorJava.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/Instantiator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/JavaConstructorInstantiator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/JavaInstantiatorProcessor.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/experimental/KotlinInstantiator.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/experimental/KotlinInstantiatorDsl.kt, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/InstantiatorTest.kt
Add CompositeInstantiator
* instantiateCompositeJavaObjectByProperty
=> Refactor propertyInstantiator as a sub-Instantiator

fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/InstantiatorTest.kt
Add an instantiate test for private constructor
* instantiatePrivateConstructor
=> Add an instantiate test for private constructor

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/FactoryMethodInstantiator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/FactoryMethodInstantiatorJava.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/Instantiator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/JavaInstantiatorProcessor.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/experimental/KotlinInstantiator.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/experimental/KotlinInstantiatorDsl.kt, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/InstantiatorTest.kt
Add factory method name in FactoryMethodInstantiator
* instantiateByFactoryMethod
* instantiateByCompanionObjectFactoryMethod
=> Add factory method name in FactoryMethodInstantiator

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ConstructorParameterPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/TypeCache.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/NestedClassTestSpecs.java
generating inner class
resolves #548 
* nestedObject
=> Add generating inner class

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/jqwik/ArbitraryUtils.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/random/Randoms.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/AnnotatedTypes.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Reflections.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/TypeCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java, fixture-monkey-api/src/main/java17/com/navercorp/fixturemonkey/api/type/AnnotatedTypes.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/util/StringUtils.java
Refactor unifying all utils as a abstract class
=> Refactor unifying all utils as an abstract class

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/KotlinPlugin.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/instantiator/KotlinInstantiator.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/instantiator/KotlinInstantiatorDsl.kt, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/InstantiatorTest.kt
Refactor moving Kotlin instantiator package
=> Refactor moving Kotlin instantiator package

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/AnnotatedTypes.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java, fixture-monkey-api/src/main/java17/com/navercorp/fixturemonkey/api/type/AnnotatedTypes.java, fixture-monkey-jakarta-validation/src/main/java/com/navercorp/fixturemonkey/jakarta/validation/introspector/JakartaValidationConstraintGenerator.java, fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationConstraintGenerator.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/type/KotlinTypes.kt
Remove all TODO tasks
* Add new implementation for generating `AnnotatedTypeVariable` in JDK 17
*existing tests
=> Remove all TODO tasks

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/JavaGetterMethodPropertySelector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/JavaGetterMethodReference.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/JavaGetterPropertySelector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/JavaGetterPropertySelectors.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/JoinJavaGetterPropertySelector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/KotlinTypeDetector.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
Add a PropertySelector for Java Getter
* setJavaGetter
* setJavaGetterInto
* setJavaGetterCollection
* setJavaGetterCollectionElement
=> Add a PropertySelector for Java Getter

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/instantiator/KotlinInstantiator.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/type/KotlinTypes.kt, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/InstantiatorTest.kt
Add instantiateBy using KotlinConstructor
* instantiateWithDefaultArgument
=> Add instantiateBy using KotlinConstructor

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/instantiator/KotlinInstantiator.kt, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/InstantiatorTest.kt
Add parameter option for using default argument
* instantiateJavaConstructorWithDefaultArgument
* instantiateConstructorWithDefaultArgument
=> Add parameter option for using default argument

config/_default/params.toml, content/en/docs/customizing-objects/apis.md, content/en/docs/customizing-objects/expressions.md, content/en/docs/fixture-monkey-options/customization-options.md, content/en/docs/generating-objects/instantiate-methods.md, content/en/docs/generating-objects/introspector.md, content/en/docs/intellij-plugin/fixture-monkey-helper.md, content/en/docs/plugins/jakarta-validation-plugin/bean-validation.md, content/en/docs/plugins/kotest-plugin/_index.md, content/en/docs/plugins/kotest-plugin/features.md, content/en/docs/plugins/kotest-plugin/property-based-testing.md, content/en/docs/plugins/kotlin-plugin/_index.md, content/en/docs/plugins/kotlin-plugin/features.md, content/en/docs/plugins/kotlin-plugin/introspectors-for-kotlin.md, content/en/docs/plugins/kotlin-plugin/kotlin-exp.md
Updates the document to v1.0. Adds new features in 1.0
- `instantiate()`, `instantiateBy()`
- JavaGetter selector
- Kotest Plugin
- Fix some minor errors & typos
=> Update document to 1.0

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt, fixture-monkey-tests/kotlin-tests/src/test/java/com/navercorp/fixturemonkey/tests/kotlin/ImmutableJavaTestSpecs.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
Add Exp extensions for array
* setExpArrayElement
* setExpNestedArrayElement
* setExpGetterArrayElement
* setExpGetterNestedArrayElement
=> Add Exp extensions for array

content/en/docs/get-started/creating-test-objects.md
Fix broken links from document.
=> Fix Document broken links

layouts/partials/header/header.html
=> Fix document version dropdown

fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java
Reduce the number of tests return different values
=> Reduce the number of tests return different values

fixture-monkey-jakarta-validation/src/main/java/com/navercorp/fixturemonkey/jakarta/validation/introspector/JakartaValidationConstraintGenerator.java, fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationConstraintGenerator.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotestInJunitTest.kt
Fix generating min-zero decimal and integer by kotest-property
* sampleMinZeroInteger
* sampleMinZeroDecimal
=> Fix generating min-zero decimal and integer by kotest-property

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/OptionTest.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java
Add pushJavaConstraintGeneratorCustomizer option
* customizeJavaConstraintGenerators
* customizeJavaConstraintGeneratorsTwice
=> Add pushJavaConstraintGeneratorCustomizer option

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java
Fix resolving JavaConstraintGenerator order
=> Fix resolving JavaConstraintGenerator order

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Constructors.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/TypeCache.java, fixture-monkey-api/src/main/java17/com/navercorp/fixturemonkey/api/type/Constructors.java, fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/ConstructorPropertiesRecordTest.java, fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/RecordTestSpecs.java
Add generating record using canonical constructor by default
* recordShouldUseCanonicalConstructor
* recordUseCompactConstructor
=> Add generating record using canonical constructor by default

.github/workflows/github-page.yml
=> Fix github-page action

docs/content/en/docs/get-started/creating-test-objects.md
=> Fix broken doc links

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FailoverIntrospector.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
Add FailoverIntrospector handling exception when declaring
*failoverIntrospectorHandlingExceptionWhenDeclaring
=> Add FailoverIntrospector handling exception when declaring

build.gradle
Fix Kotlin module having a fixed dependency on JDK 8
=> Fix Kotlin module having a fixed dependency on JDK 8

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/FilteredCombinableArbitrary.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ResolvedCombinableArbitrary.java
Add more detailed messages if generation fails
=> Add more detailed messages if generation fails

fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeSetDecomposedValueManipulator.java
=> Fix setting child

CONTRIBUTING.md
Adds document contribution guide on CONTRIBUTING.md.
=> Add document contribution guide

docs/content/v1.0.x/release-notes/_index.md, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/TypedExpressionGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/TypedPropertySelector.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/MonkeyManipulatorFactory.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeCustomizerManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectNode.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java
Add customizeProperty API in ArbitraryBuilder to customize generated value
* customizePropertyFilter
* customizePropertySet
Yes
=> Add customizeProperty API in ArbitraryBuilder to customize generated value

docs/content/v1.0.x/release-notes/_index.md, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptions.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
Add customizing Wildcard type in an option
* sampleCustomizedWildcardType
Yes
=> Add customizing Wildcard type in an option

docs/content/v1.0.x/release-notes/_index.md, fixture-monkey-kotest/src/main/kotlin/com/navercorp/fixturemonkey/kotest/ArbExtension.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt, fixture-monkey-tests/kotlin-tests/build.gradle.kts, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotestInJunitTest.kt, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotestInKotestTest.kt
Add better support Kotest
* Refactor `giveMeArb` more Kotlin-like
* Add `setArb` API 
* sampleSetArb
Yes
=> Add better support Kotest

fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/ValueClassTest.kt
Add a test for fixing a value class property
* valueClassPropertyFixed
* None required
=> Add a test for fixing a value class property

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/KotlinPlugin.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/generator/InterfaceKFunctionPropertyGenerator.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/instantiator/KotlinInstantiator.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/CompanionObjectFactoryMethodIntrospector.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/KotlinPropertyArbitraryIntrospector.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/KotlinPropertyCache.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/type/KotlinTypeCache.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/type/KotlinTypeExtensions.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/type/KotlinTypes.kt
Add better support for Kotlin types
*existing tests
It is for internal use
=> Add better support for Kotlin types

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/exception/Exceptions.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/instantiator/JavaInstantiatorProcessor.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BeanArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FieldReflectionArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ConstructorParameterPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Reflections.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/TypeCache.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java
Refactor using constructor reflections in TypeCache
* will update in publishing PR
=> Refactor using constructor reflections in TypeCache

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/ExactPropertyMatcher.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/IntersectMatcher.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/Matcher.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/UnionMatcher.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptions.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/matcher/Matchers.kt
Add methods to combine two matchers
Yes
=> Add methods to combine two matchers

docs/content/v1.0.x/docs/generating-objects/instantiate-methods.md
The indent didn't fit and we thought it would be confusing, so I fixed it.
Using command `npm start`
We do not update the document because it is a request for Korean translation.
=> Fix document code indent

docs/content/v1.0.x-kor/docs/get-started/creating-test-objects-without-lombok.md
creating-test-objects-without-lombok page translation for kor
related to #864 
`npm start`
=> Add creating-test-objects-without-lombok page of get-started section for kor doc

docs/content/v1.0.x/release-notes/_index.md
=> Fix doc broken release note

docs/content/v1.0.x-kor/docs/customizing-objects/apis.md
Fixture-Customization-APIs page translation for kor
related to #864 
=> Add Fixture customization apis page for kor doc

buildSrc/src/main/kotlin/com/navercorp/fixturemonkey/gradle/plugin/MavenPublishConventionsPlugin.kt
Fix not signing when publishing to MavenLocal
Not required
Not required
=> Fix not signing when publishing to MavenLocal

docs/content/v1.0.x/docs/fixture-monkey-options/customization-options.md, docs/content/v1.0.x/docs/fixture-monkey-options/generation-options.md, docs/content/v1.0.x/docs/fixture-monkey-options/other-options.md
- Fix duplicate header in generation options
- Enhance headers to be more specific and rearrange options.
=> Update doc options section

docs/content/v1.0.x-kor/docs/customizing-objects/expressions.md
Expressions page translation for kor
related to #864
=> Add Expressions page for kor doc

docs/content/v1.0.x-kor/docs/customizing-objects/arbitrary.md
related to #864
translate `Customizing random values with Arbitrary` section in `Customizing Objects` part into Korean
=> Add 'Customizing random values with Arbitrary' section for kor doc

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorContext.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectNode.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java
Refactor ObjectNode owning PropertyPath
Nope
=> Refactor ObjectNode owning PropertyPath

docs/content/v1.0.x/release-notes/_index.md
Add a missing release note in 1.0.14
=> Add a missing release note in 1.0.14

docs/content/v1.0.x-kor/docs/customizing-objects/innerspec.md
=> Add innerSpec page of customizing-objects section for kor doc

docs/content/v1.0.x-kor/docs/plugins/jakarta-validation-plugin/bean-validation.md, docs/content/v1.0.x-kor/docs/plugins/jakarta-validation-plugin/features.md
Summary
Translation of Jakarta Validation Plugin documents for Koreans.
This korean translation works is related to https://github.com/naver/fixture-monkey/issues/864
How Has This Been Tested?
Checked out the document pages with npm.
Is the Document updated?
Everyting is updated.
=> Translation of JakartaValidationPlugin documents

docs/content/v1.0.x-kor/docs/intellij-plugin/fixture-monkey-helper.md
Translate IntelliJ plugin section to korean.
This work is related to #864
Checked out the document pages with `npm start`.
Everyting is updated.
=> Translate IntelliJ plugin section to korean

docs/content/v1.0.x-kor/docs/plugins/jackson-plugin/_index.md, docs/content/v1.0.x-kor/docs/plugins/jackson-plugin/features.md, docs/content/v1.0.x-kor/docs/plugins/jackson-plugin/jackson-annotations.md, docs/content/v1.0.x-kor/docs/plugins/jackson-plugin/jackson-object-arbitrary-introspector.md
Translation of Jackson Plugin documents for Koreans.
This korean translation works is related to #864 
Checked out the document pages with npm.
Everyting is updated.
=> Translation of Jackson Plugin documents

docs/config/_default/menus/menus.v1-0-0-kor.toml, docs/content/v1.0.x-kor/release-notes/_index.md, docs/content/v1.0.x/docs/fixture-monkey-options/generation-options.md
- Fix doc menu & release-note
- Fix errors in generation-options page.
=> Fix doc menu & release-note

docs/layouts/partials/header/header.html
- Fix doc header link to permalink
=> Fix doc header link to permalink

docs/config/_default/languages.toml, docs/layouts/partials/header/header.html
=> Fix doc language dropdown

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyUtils.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/KPropertyProperty.kt
Add missing equals and hashCode to property
Not required
=> Add missing equals and hashCode to property

docs/config/_default/languages.toml
Fix doc broken get started link.
=> Fix doc get started link

docs/content/v1.0.x-kor/release-notes/_index.md, docs/content/v1.0.x/release-notes/_index.md, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java
Fix register working on assignable type
- registerAssignableType
Yes
=> Fix register working on assignable type

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ArbitraryTraverser.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/TraverseContext.java
Refactor ArbitraryTraverser integrate rootNode and childNode
No needed
=> Refactor ArbitraryTraverser integrate rootNode and childNode

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ConstantIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptions.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ConstantProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/FieldPropertyGenerator.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/MutableJavaTestSpecs.java
Add ConstantProperty for constants
It is not effected
Not needed
=> Add ConstantProperty for constants

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
Refactor candidateConcretePropertyResolver insert first
It is not effected
Not effected
=> Refactor candidateConcretePropertyResolver insert first

build.gradle.kts, fixture-monkey-benchmarks/fixture-monkey-benchmark-kotlin/build.gradle.kts, fixture-monkey-junit-jupiter/build.gradle.kts, fixture-monkey-kotest/build.gradle.kts, fixture-monkey-kotlin/build.gradle.kts, fixture-monkey-starter-kotlin/build.gradle.kts, fixture-monkey-tests/kotlin-concurrent-tests/build.gradle.kts, fixture-monkey-tests/kotlin-tests/build.gradle.kts
Fix loading Kotlin plugin only once.
not needed
=> Fix loading Kotlin plugin only once

docs/content/v1.0.x-kor/release-notes/_index.md, docs/content/v1.0.x/release-notes/_index.md, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/SealedClassTest.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeSetDecomposedValueManipulator.java
Fix `sealedInterface` set not working after thenApply
* sealedInterfaceApplySet
Yes
=> Fix sealed interface set not working after thenApply

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/NullInjectCombinableArbitrary.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/FunctionalInterfaceContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/JavaDefaultArbitraryGeneratorBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FunctionalInterfaceArbitraryIntrospector.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptions.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/KotlinPlugin.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/type/KotlinTypeCache.kt, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt, fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java
Support Java, Kotlin Functional Interface.
- Supplier
- Function
- Kotlin Function
* sampleFunction
* decomposeFunction
* kotlinLambda
* kotlinLambdaOnlyReturnType
* kotlinLambdaReturnType
* setJustKotlinLambda
Later
=> Support Java, Kotlin Functional Interface

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/ContainerCombinableArbitrary.java, fixture-monkey-benchmarks/fixture-monkey-benchmark/src/jmh/java/com/navercorp/fixturemonkey/ManipulationBenchmark.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ResolvedCombinableArbitrary.java
Add regenerate the ObjectTree when is filtered
existing tests
No
=> Add regenerate the ObjectTree when is filtered

docs/content/v1.0.x-kor/docs/generating-objects/generating-interface.md, docs/content/v1.0.x/docs/generating-objects/generating-interface.md
Add a new article to illustrate how to generate the interface.
=> Add interface documentation

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/plugin/InterfacePlugin.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
Add the flexible option for complex usage in InterfacePlugin
* complexAbstractExtendsReturnsFirst
* complexAbstractExtendsReturnsSecond
Not yet
=> Add the flexible option for complex usage in InterfacePlugin

docs/content/v1.0.x-kor/docs/customizing-objects/interface.md, docs/content/v1.0.x/docs/customizing-objects/interface.md
Add customizing interface documentation
=> Add customizing interface documentation

.github/workflows/deploy.yml
Publish to sonatype when release is published
=> Publish to sonatype when release is published

fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/generator/ElementJsonSubTypesObjectPropertyGenerator.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/generator/PropertyJsonSubTypesObjectPropertyGenerator.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/property/ElementJsonSubTypesConcreteTypeResolver.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/property/PropertyJsonSubTypesConcreteTypeResolver.java
Add CandidateConcreteTypeResolvers for Jackson
existing tests
later
=> Add CandidateConcreteTypeResolvers for Jackson

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/ContainerCombinableArbitrary.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/ContainerCombineArbitraryBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/FilteredCombinableArbitrary.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/NullInjectCombinableArbitrary.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/TraceableCombinableArbitrary.java, fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/arbitrary/ArbitraryTest.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/MonkeyManipulatorFactory.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/Values.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/experimental/ExperimentalArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ResolvedCombinableArbitrary.java
Add convenient unique APIs
- unique
-  customizePropertyUnique
- containerUnique
-  containerMappingNotUnique
Later
=> Add convenient unique APIs

docs/content/v1.1.x-kor/docs/plugins/kotlin-plugin/introspectors-for-kotlin.md, docs/content/v1.1.x/docs/plugins/kotlin-plugin/introspectors-for-kotlin.md, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/MatchPropertyGenerator.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/KotlinPlugin.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/instantiator/KotlinInstantiator.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/KotlinAndJavaCompositeArbitraryIntrospector.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/KotlinDurationIntrospector.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/PrimaryConstructorArbitraryIntrospector.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/KotlinConstructorParameterProperty.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/KotlinConstructorParameterPropertyGenerator.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/KotlinPropertyCache.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/type/KotlinTypeCache.kt, fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyKotlinJacksonTest.kt
Refactor separate Kotlin property and Java property
- existing tests
Yes
=> Refactor separate Kotlin property and Java property

fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java
Add customizeProperty API as maintained
=> Add customizeProperty API as maintained

fixture-monkey-junit-jupiter/src/main/java/com/navercorp/fixturemonkey/junit/jupiter/extension/FixtureMonkeySeedExtension.java, fixture-monkey-junit-jupiter/src/test/java/com/navercorp/fixturemonkey/junit/jupiter/extension/FixtureMonkeySeedExtensionTest.java
Fix seed setting as annotated
Later
=> Fix seed setting as annotated

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/CompositeTypeDefinition.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ConcreteTypeDefinition.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/DefaultTypeDefinition.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/tree/ObjectTreeNode.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeSetDecomposedValueManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/DefaultNodeResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/IdentityNodeResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/MetadataCollector.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectNode.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/TraverseContext.java
Refactor for lazy ObjectNode generation
No needed
=> Refactor for lazy ObjectNode generation

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/JavaGetterPropertyFieldNameResolver.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/JavaGetterPropertySelectors.java, fixture-monkey-api/src/main/java17/com/navercorp/fixturemonkey/api/experimental/JavaGetterPropertyFieldNameResolver.java, fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/ConstructorPropertiesRecordTest.java, fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/RecordTestSpecs.java
Add support javaGetter for is prefix boolean property
* setIsPrefixWrapperBoolean
* setIsPrefixPrimitiveBoolean
No needed
=> Add support javaGetter for is prefix boolean property

docs/content/v1.1.x-kor/release-notes/_index.md, docs/content/v1.1.x/release-notes/_index.md, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeSetDecomposedValueManipulator.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectNode.java
Fix set a recursive object
* setSelfRecursiveObject
Yes
=> Fix set a recursive object

docs/content/v1.1.x-kor/release-notes/_index.md, docs/content/v1.1.x/release-notes/_index.md, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java
Add a missing giveMeJavaBuilder with an object parameter
Yes
=> Add a missing giveMeJavaBuilder with an object parameter

docs/content/v1.1.x-kor/release-notes/_index.md, docs/content/v1.1.x/release-notes/_index.md, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/InterfaceTestSpecs.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectNode.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/TraverseContext.java
Fix setting recursive implementations of self reference object
* setListRecursiveImplementations
Yes
=> Fix setting recursive implementations of self reference object

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/jqwik/JqwikJavaArbitraryResolver.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
Fix generating empty String with `@Size` annotation
- sizeZero
No needed
=> Fix generating empty String with @Size annotation

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/ObjectBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyContext.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyContextBuilder.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyGeneratorContext.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyExtensions.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/JavaTypeArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryBuilderContext.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/JavaTypeDefaultTypeArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/MonkeyManipulatorFactory.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectNode.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/TraverseContext.java
Same PR as https://github.com/naver/fixture-monkey/pull/1058
No
=> Refactor scoped context

docs/content/v1.1.x-kor/release-notes/_index.md, docs/content/v1.1.x/release-notes/_index.md, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectNode.java
Fix not registering size API if decomposing
- setAndRegister
Yes
=> Fix not registering size API if decomposing

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/DefaultTreeMatcherMetadata.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/TreeMatcher.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/TreeMatcherMetadata.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/TreeMatcherOperator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/BuilderContextInitializer.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptions.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryBuilderContext.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ResolvedCombinableArbitrary.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/MetadataCollector.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/TraverseContext.java
Add `customizeValidOnly` option
* customizerValidOnly
* customizerValidOnlyBuilderValidOnlyFirst
Later
=> Add customizeValidOnly option

docs/content/v1.1.x-kor/release-notes/_index.md, docs/content/v1.1.x/release-notes/_index.md, fixture-monkey-junit-jupiter/src/main/java/com/navercorp/fixturemonkey/junit/jupiter/extension/FixtureMonkeySeedExtension.java
Add enrich the failed test log with seed
Yes
=> Add enrich the failed test log with seed

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptions.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/tree/DefaultTraverseNode.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/tree/TraverseContext.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryBuilderContext.java
Remove FixtureMonkeyOptions dependency with TraverseContext
No needed
=> Remove FixtureMonkeyOptions dependency with TraverseContext

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ElementProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/MapKeyElementProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/MapValueElementProperty.java
Fix ElementProperty, MapKeyValueElementProperty equals and hashCode
existing tests
No needed
=> Fix ElementProperty, MapKeyValueElementProperty equals and hashCode

docs/content/v1.1.x-kor/release-notes/_index.md, docs/content/v1.1.x/release-notes/_index.md, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/random/Randoms.java, fixture-monkey-junit-jupiter/src/main/java/com/navercorp/fixturemonkey/junit/jupiter/extension/FixtureMonkeySeedExtension.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java
Fix set seed indirectly to prepare deterministic testing
*existing tests
Yes
=> Fix set seed indirectly to prepare deterministic testing

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/tree/TraverseContext.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryBuilderContext.java
Refactor TraverseContext dependency on generation
existing tests
Not needed
=> Refactor TraverseContext dependency on generation

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArrayContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultSingleContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/EntryContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/FunctionalInterfaceContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/MapContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/OptionalContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/SetContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/StreamContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ContainerElementProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/DefaultContainerElementProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ElementProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/MapKeyElementProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/MapValueElementProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyPath.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/TypeParameterProperty.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/generator/JsonNodeContainerPropertyGenerator.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/plugin/JacksonPlugin.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/property/ElementJsonSubTypesConcreteTypeResolver.java, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/generator/PairContainerPropertyGenerator.kt, fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/generator/TripleContainerPropertyGenerator.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ContainerElementPredicate.java
Add TypeParameterProperty and ContainerElementProperty and deprecate ElementProperty
* exising tets
Later
=> Add TypeParameterProperty and ContainerElementProperty

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultSingleContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/SetContainerPropertyGenerator.java
Fix maintain backward compatibility for raw type List or Set
existing tests
No needed
=> Fix maintain backward compatibility for raw type List or Set

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultSingleContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/MapContainerPropertyGenerator.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/SetContainerPropertyGenerator.java
Refactor container element to raw type as String type 
Later
=> Refactor container element to raw type as String type

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/random/Randoms.java
Remove JqwikException
Not needed
=> Remove JqwikException

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ConcreteTypeCandidateConcretePropertyResolver.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ConcreteTypeProperty.java, fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/InterfaceCandidateConcretePropertyResolver.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/property/ElementJsonSubTypesConcreteTypeResolver.java, fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/property/PropertyJsonSubTypesConcreteTypeResolver.java
Add ConcreteTypeProperty
*existing tests
Not needed
=> Add ConcreteTypeProperty

fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpecState.java
Fix InnerSpec inner API
* innerSpecInner
Later
=> Fix InnerSpec inner API

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/plugin/SimpleValueJqwikPlugin.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/SimpleValueJqwikPluginTest.kt
Fix modifying the number option in `SimpleValueJqwikPlugin`
* setPositiveMinNumberReturnsPositive
* setNegativeMaxNumberReturnsNegative
Later
=> Fix modifying the number option in SimpleValueJqwikPlugin

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/expression/KotlinExpressionDsl.kt, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpec.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpecState.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/expression/DeclarativeExpression.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/expression/DefaultDeclarativeExpression.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/StartNodePredicate.java
Add DeclarativeExpression
Later
=> Add DeclarativeExpression

fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/MonkeyManipulatorFactory.java
Refactor use PropertySelector as primary expression
Later
=> Refactor use PropertySelector as primary expression

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/type/KotlinTypeExtensions.kt, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/ValueClassTest.kt
Fix instantiate with value class parameter
* factoryParameterValueClass
Later
=> Fix instantiate with value class parameter

fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/KotlinPlugin.kt, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/SealedClassTest.kt
Fix generating Kotlin sealed object type definition
* sealedObject
* sealedObjectThenApply
Later
=> Fix generating Kotlin sealed object type definition

docs/config/_default/menus/menus.v0-6-0.toml, docs/config/_default/menus/menus.v1-0-0-kor.toml, docs/config/_default/menus/menus.v1-0-0.toml, docs/config/_default/menus/menus.v1-1-0-kor.toml, docs/config/_default/menus/menus.v1-1-0.toml, docs/layouts/index.html
=> Fix broken landing page

docs/content/v1.1.x-kor/docs/plugins/interface-plugin/_index.md, docs/content/v1.1.x-kor/docs/plugins/interface-plugin/features.md, docs/content/v1.1.x/docs/plugins/interface-plugin/_index.md, docs/content/v1.1.x/docs/plugins/interface-plugin/features.md
Add new InterfacePlugin documentation
=> Add new interface document

docs/content/v1.1.x-kor/docs/introduction/overview.md, docs/content/v1.1.x/docs/introduction/overview.md
Add more detail information about Fixture Monkey in overview
=> Add more detail information about Fixture Monkey in overview

docs/content/v1.1.x-kor/docs/customizing-objects/arbitrary.md, docs/content/v1.1.x-kor/docs/customizing-objects/expressions.md, docs/content/v1.1.x-kor/docs/customizing-objects/innerspec.md, docs/content/v1.1.x-kor/docs/customizing-objects/interface.md, docs/content/v1.1.x/docs/customizing-objects/apis.md, docs/content/v1.1.x/docs/customizing-objects/arbitrary.md, docs/content/v1.1.x/docs/customizing-objects/innerspec.md, docs/content/v1.1.x/docs/customizing-objects/interface.md, docs/content/v1.1.x/docs/customizing-objects/path-expressions.md, docs/content/v1.1.x/docs/get-started/creating-objects-without-lombok.md, docs/content/v1.1.x/docs/get-started/creating-objects.md
Fix menu naming
Fix sidebar menu name and re-ordering
=> Fix menu naming

docs/content/v1.1.x-kor/docs/introduction/overview.md, docs/content/v1.1.x/docs/introduction/overview.md
Refactor overview page
- Updated with more natural expressions
- re-ordering
=> Refactor overview page

docs/content/v1.1.x-kor/docs/migration-guide/migration-guide.md, docs/content/v1.1.x/docs/migration-guide/migration-guide.md
Improve migration guide documentation
=> Improve migration guide documentation

docs/content/v1.1.x-kor/docs/cheat-sheet/faq.md, docs/content/v1.1.x/docs/cheat-sheet/faq.md
Improve cheat sheet sections documentation
=> Improve cheat sheet sections documentation

docs/content/v1.1.x-kor/docs/customizing-objects/apis.md, docs/content/v1.1.x-kor/docs/customizing-objects/arbitrary.md, docs/content/v1.1.x-kor/docs/customizing-objects/innerspec.md, docs/content/v1.1.x-kor/docs/customizing-objects/interface.md, docs/content/v1.1.x-kor/docs/customizing-objects/path-expressions.md, docs/content/v1.1.x-kor/docs/customizing-objects/quick-start-guide.md, docs/content/v1.1.x/docs/customizing-objects/apis.md, docs/content/v1.1.x/docs/customizing-objects/arbitrary.md, docs/content/v1.1.x/docs/customizing-objects/innerspec.md, docs/content/v1.1.x/docs/customizing-objects/interface.md, docs/content/v1.1.x/docs/customizing-objects/path-expressions.md, docs/content/v1.1.x/docs/customizing-objects/quick-start-guide.md
Improve customization APIs documentation
=> Improve customization APIs documentation

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/tree/TraverseContext.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryBuilderContext.java, fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java
Fix size API within register that applies to root type
* registerSizeLessThanThree
No needed
=> Fix size API within register that applies to root type

fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/plugin/SimpleValueJqwikPlugin.java, fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/PluginTest.java, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/PluginTest.kt, fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/SimpleValueJqwikPluginTest.kt
Fix bugs in SimpleValueJqwikPlugin if minSize is greater than default max size
* simpleValueJqwikPluginMinusDaysFromTodayGreaterThanDefault
* simpleValueJqwikPluginMinContainerSizeGreaterThanDefault
* simpleValueJqwikPluginMinStringLengthGreaterThanDefault
* simpleValueJqwikPluginMinNumberValueGreaterThanDefault
No needed
=> Fix bugs in SimpleValueJqwikPlugin if minSize is greater than default max size
