naver/fixture-monkey

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryValue.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java
- ArbitraryBuilder 에서 바로 sample 을 하거나 build 로 반환된 Arbitrary 에서 sample 을 호출할 때는 문제가 없습니다. (일반적인 사용방법)
- build 된 Arbitrary 에서 sampleStream 이나 다른 액션을 통해 반환 받은 객체로 sampling 을 하면 Validation 을 안타게 됩니다.
- 그래서 ArbitararyGenerator 에서 내부 Arbitrary 를 생성할 때 filter 로 validation 을 추가해 항상 Validation 을 타도록 합니다.
---
- ArbitraryBuilder 가 build 시 반환하는 Arbitrary 를 관리하는 방식을 변경하긴 해야될거 같습니다. 
- 다행히 공개 클래스는 아니라서 구조 변경에 자유롭긴 합니다.
> Fix ArbitraryBuilder generated Arbitrary not affected Validator any with action

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryTree.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryValue.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java
우선 Arbitrary를 반환값으로 가지는 경우만 처리했습니다.
Arbitrary를 반환할 때 ArbitraryValue를 반환해서 `sample`, `sampleStream`을 실행하는 시점을 추적합니다.
값을 반환하는 `sample`, `sampleStream`를 실행하는 시점에서 내부 동작은 모두 Lazy하고 모든 연산이 실행됩니다.
Validation 실패 원인을 로깅하기 위해 같은 ArbitraryValue 객체들은 violations를 공유합니다.
동시에 실행하는 경우는 거이 없겠지만, 있을 수도 있으므로 ConcurrentHashMap을 구현체로 사용합니다.
공유하더라도 Validation 실패하는 경우이므로 문제가 없습니다.
> Refactor ArbitraryValue methods return Arbitrary

- fixture-monkey-starter/build.gradle
- fixture-monkey-starter/gradle.properties
- fixture-monkey-starter/src/main/resources/logback.xml
- fixture-monkey-starter/src/test/java/com/navercorp/fixturemonkey/starter/FixtureMonkeyStarterTest.java
- settings.gradle
- starter dependency 로 바로 시작할 수 있는 starter 모듈을 추가합니다.
- 빈 프로젝트에서 fixture-monkey dependency 만 추가해서 바로 해보려니까 logger 구현체가 없어서 에러가 나네요
- logger 구현체도 직접 추가해줘야 되고, Validation 을 적용하기 위해서는 Validator 구현체도 직접 지정해줘야 되는 불편함이 있어서 이들의 dependency 를 바로 적용할 수 있는 fixture-monkey-starter 모듈을 추가합니다.
- logback 의존성이나 validator 구현체를 다른걸로 사용하고 싶은 사용자는 starter 를 의존하지 않고 직접 지정하면 됩니다.
> Add fixture-monkey-starter module

- build.gradle
- fixture-monkey-autoparams/build.gradle
- fixture-monkey-engine/build.gradle
- fixture-monkey-engine/gradle.properties
- fixture-monkey-mockito/build.gradle
- settings.gradle
- fixture-monkey-engine 모듈을 추가하고 junit-plateform-engine 및 jqwik-engine 을 의존시킵니다.
- 우선 라이브러리 의존만 정리하고, 다음 단계로 engine 과 관련된 로직을 이동시킵니다.
- 0.4.0 반영 합니다.
> Add fixture-monkey-engine to split junit/jqwik engine

- fixture-monkey-api/build.gradle
- fixture-monkey-api/gradle.properties
- settings.gradle
확장을 지원할 spi Interface 들을 제공하는 fixture-monkey-api 모듈을 추가합니다.
fixture-monkey 에서 확장을 지원할 인터페이스는 여기에 추가하고, 기존 인터페이스는 @Deprecated 처리합니다.
fixture-monkey-jackson, fixture-monkey-mockito 도 fixture-monkey 를 바로 의존하는 것이 아니라 fixture-monkey-api 를 의존하고 필요한 구현체를 제공하도록 수정합니다.
Deprecated 된 fixture-monkey 의 인터페이스는 0.5.0 에서 제거합니다.
> Add fixture-monkey-api module for spi interfaces

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/CallbackList.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/CallbackOperation.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java
callback 연산을 캡슐화한 CallbackOperation을 추가합니다.
이전에 @acktsap 님이 의견 주셨던 내용 반영해서 CallbackOperationBuilder에서 연산 종류에 따라 별도로 처리할 수 있는 빌더 메소드를 추가했습니다.
연산을 변환하는 transform도 추가했습니다.
> Add CallbackOperation for better extension

- README.md
문서는 doc 브랜치로 관리하여 문서에 기여하신 Contributor가 정상적으로 표시되지 않습니다.
이를 해결하기 위해 README에 contributor를 별도로 나타냅니다.
contributor들이 많아지면 별도의 md 파일로 관리할 예정입니다.
> Add Contributor in Readme

- fixture-monkey-autoparams/build.gradle
- fixture-monkey-autoparams/src/test/java/com/navercorp/fixturemonkey/autoparams/test/FixtureMonkeyValueCustomizerTest.java
- fixture-monkey-engine/build.gradle
- fixture-monkey-engine/src/main/java/com/navercorp/fixturemonkey/engine/jupiter/extension/FixtureMonkeySessionExtension.java
- fixture-monkey-starter/build.gradle
- fixture-monkey-starter/src/test/java/com/navercorp/fixturemonkey/starter/FixtureMonkeyStarterTest.java
- fixture-monkey/build.gradle
- jupiter 테스트에서 사용할 `FixtureMonkeySessionExtension` 을 추가
- JUnit 5 의 @ExtendWith 로 선언해서 사용 가능
- `FixtureMonkeySessionExtension` 는 테스트 시작과 끝의 라이프 사이클에 JqwikSession 라이프 사이클을 적용
- `FixtureMonkeySessionExtension` 선언하지 않아도 테스트 동작에 문제는 없지만, JqwikSession 라이프 사이클을 적용할 경우 불필요한 내부 static cache 를 비워주기 때문에 Fixture Monkey 로 객체 생성하는 테스트가 많을 수록 성능적으로 유리함
- 또한 JqwikSesssion 라이프 사이클을 사용해서 jqwik 의 statistics reporting 기능 확장도 추가로 가능
> Introduce FixtureMonkeySessionExtension for jupiter

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java
This PR ensures the KFixtureMonkey instance is a non-null type.
So, fix the warning below. This warning is propagated to your source code.
I think that specifying it as non-null type on KFixtureMonkey(like below) would be a workaround.
```kt
object KFixtureMonkey {
fun create(): FixtureMonkey = KFixtureMonkeyBuilder().build()
}
```
But, specifying the `@Nonnull` annotation looks proper solution.
> Specify FixtureMonkey instance as a non-null type

- build.gradle
- fixture-monkey-api/build.gradle
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/random/Randoms.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/seed/Randoms.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitrarySpecAny.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ContainerSizeConstraint.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/DefaultIterableSpec.java
jqwik 의 Random 과 같은 seed 로 Random 생성을 하기 위해 fixture-monkey-api 에 Randoms 를 추가합니다.
Randoms 는 jqwik-engine 의 SourceOfRandomness 를 같이 사용합니다.
그리고 ThreadLocalRandom 을 사용하던 코드들을 새로 추가한 Randoms 를 사용하도록 수정합니다.
다음 작업으로 seed 를 고정 셋팅할 수 있는 설정 기능을 추가합니다.
> Add Randoms for using same seed random with jqwik engine SourceOfRandomness

- fixture-monkey-api/build.gradle
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryIntrospectorContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryTypeIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/TimeArbitraryIntropector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/TimeArbitraryIntrospector.java
- ArbitraryIntrospector 인터페이스를 추가합니다.
- 타입에 따른 기본 Arbitrary 를 받아 Annotation 을 포함한 정보들을 읽어서 추가적인 제약 및 조작을 부여할 수 있습니다.
- 이후 PR 로 기본 형태가 지원될 것이며, 이 기본 형태를 사용자가 확장해서 custom 할 수 있습니다.
> Introduce ArbitraryIntrospector interfaces

- fixture-monkey-api/build.gradle
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyDescriptorProperty.java
- fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/property/PropertyDescriptorPropertyTest.java
- fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/property/PropertyValue.java
지금까지 Field 를 기준으로 애노테이션을 식별하고 메소드를 기준으로 식별할 수 없었다
메소드를 기준으로 annotation 등을 관리하는 PropertyDescriptorProperty 를 추가한다.
> Introduce PropertyDescriptorProperty

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryNode.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArrayArbitraryNodeGenerator.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/DefaultContainerArbitraryNodeGenerator.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/MapArbitraryNodeGenerator.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ComplexManipulatorTest.java
https://github.com/naver/fixture-monkey/pull/85 에서 처럼 set 연산을 실행할 때 입력한 객체를 분해해서 Virtual Class Tree에 반영할 때 로직을 수정합니다.
Set을 실행할 때 객체를 분해하지 않고 일관성 있는 로직을 위해 기존의 traverse시에 decompose 로직을 활용하도록 수정합니다.
수정하면서 컨테이너 생성 로직에 있었던 버그를 발견해 수정합니다.
---
Modify the logic when decomposing the input object when executing the set operation as shown in #85 and reflecting it in the Virtual Class Tree.
When executing Set, modify the object to utilize the compose logic in the existing traverse for consistent logic without decomposing it.
While modifying, find and correct the bug that was in the container creation logic.
다음 PR에서는 `apply`/`acceptIf`를 연산 (Manipulator)로 전환할 예정입니다.
> Refactor set using traverse

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryApply.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ComplexManipulatorTest.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java
apply와 acceptIf 연산을 BuilderManipulator 구현체인 `ArbitraryApply` 객체를 통해 실행하도록 수정합니다.
다른 연산과 동일한 구조로 변경하여 일관성을 보장합니다.
다음 PR에서는 `fixed`를 BuilderManipulator 구현체를 통해 실행하도록 수정할 예정입니다.
---
Modify the `apply` and `acceptIf` operations to run through the 'ArbitraryApply' object, the BuilderManipulator implementation.
It ensures consistency by changing it to the same structure as other operations.
In the next PR, `fixed` will be modified to run through the BuilderManipulator implementation.
> Refactor apply, acceptIf as manipulator

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryTree.java
`fixed`를 `set` 연산을 통해 설정하도록 변경합니다.
내부적으로는 이전과 동일하게 동작합니다.
resolves https://github.com/naver/fixture-monkey/issues/81
> Refactor fixed using set

- fixture-monkey-kotlin/build.gradle
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerator.kt
- fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGeneratorTest.kt
- fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGeneratorTestSpecs.kt
표현식을 만들어주는 kotlin DSL을 추가합니다.
필드 이름을 변경할 때 IDE의 `Refactor` 기능으로 일괄 수정이 가능해집니다.
필드 명을 유지한채로 변경하면 필드 타입을 변경하면 타입이 맞지 않으므로 IDE에서 에러를 확인할 수 있습니다.
e.g. `List` → `Set`, `List<List>>` → `List`, `Person` →`Dog` 으로 변경하면 에러가 납니다.
필드 접근 방식과 유사한 연산자 `..`와 일반적인 메소드 (`property`, `method`) 를 지원합니다.
> Add DslBuilder

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerator.kt
- fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGeneratorJavaTestSpecs.java
- fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGeneratorTest.kt
1. 자바를 지원하기 위해 `KFunction`이 입력한 경우를 처리합니다.
2. List 필드에서 다른 필드로 변경시에 타입 체킹이 안되는 문제를 Generic 타입을 2개로 변경하여 해결합니다
> Add getter support for Java

- fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyJacksonArbitraryGeneratorTest.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/ExpressionSpec.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ExpressionSpecTest.java
현재 구조 기준으로 ExpressionGenerator 를 generate 할 때 타입에 따른 기존의 FieldNameResolver 를 사용해서 속성 적용을 할 수 있도록 어댑팅 합니다.
FiledNameResolver 를 어댑팅해서 ExressionGenerator generate 를 지원하는 기능은 구조 개선 후 제거될 예정입니다.
타입에 따른 적절한 PropertyNameResolver 를 선택할 수 있어야 하기 때문에 ExpressionGenerator 의 generate 실행은 더 안쪽 실행으로 들어가야할 필요가 있습니다. 이에 따른 구조의 변경이 필요합니다.
점진적으로 구조를 개선하도록 하겠습니다.
> Apply ExpressionGenerator with legacy FieldNameResolver

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/TypeReference.java
- fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/type/TypeReferenceTest.java
Generics 를 지원하기 위한 TypeReference 를 추가합니다.
Property 등을 재 구성 하는 과정에 TypeReference 지원이 같이 고려되어야 이후에 breaking 을 최소화할 수 있을거 같아 현시점에서 같이 반영합니다.
> Introduce TypeReference

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryTypeIntrospectDelegator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/CompositeArbitraryTypeIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/EnumTypeIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/UuidTypeIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/ExactTypeMatcher.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/Matcher.java
- fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryIntrospectorResultTest.java
- fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryTypeIntrospectDelegatorTest.java
- fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/matcher/ExactMatcherTest.java
Type 외에 다른 요소로도 Matching 을 판단할 수 있기 때문에
TypeMatcher 를 Matcher 로 이름 변경합니다.
> Rename TypeMatcher to Matcher

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java
- fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/type/TypesTest.java
TypeReference 를 통한 Type 으로 Generics 를 식별하기 위한 유틸을 추가합니다.
우선 Type 에서 Class 를 도출하는 Util 메소드만 추가했으며 이 PR 이후 Generics 등을 판단하는 유틸 메소드들을 추가할 예정입니다.
> Introduce Types utils for generics

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BooleanTypeIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/EnumTypeIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/Matchers.java
조립할 수 있는 형태로 지원하기 위해 Matcher 구현을 분리합니다.
> Extract type for Matchers implements

- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/generator/JacksonArbitraryGenerator.java
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/ArbitraryGenerator.java
`fieldsByPropertyName` 에서 생성하고자 하는 타입 (최상위 객체)의 필드만 조회하여 자식 객체의 필드명을 표현식으로 변경할 때 `@JsonProperty`가 적용되지 않는 문제를 해결합니다.
> Fix resolveExpression working in nested fields

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt
- fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGeneratorsTest.kt
- fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyExtensionsTest.kt
다음과 같은 표현식을 지원합니다.
1. `set(Exp(Dog::getName), "name")`
2. `set(Dog::getName, "name")`
3. `set(Exp<Dog>() into Dog::getName, "name")`
> Refactor improving usability type-safe expression generate DSL

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java
실제 사용하는 곳이 `copy` 밖에 없고 `copy` 내에서는 값을 복사해서 넘겨주므로 의미가 없습니다.
생성자 내에서 복사한다는 것을 예측하기 어려우므로 제거합니다.
> Refactor not copying BuilderManipulator

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryNullity.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/SimpleManipulatorTest.java
연산 실행을 지연하지 않고 즉시 실행하는 `apply` 메소드를 구현 상세사항을 감추기 위해서 하나의 public 메소드로 노출합니다.
인터페이스가 달라졌지만 클라이언트는 동일하게 사용할 수 있으므로 별도 `@Deprecated` 마킹은 하지 않았습니다.
[찾아본 레퍼런스](https://github.com/spring-projects/spring-framework/blob/e85001f332bc4627a094cd2b57973e8eea370c81/spring-core/src/main/java/org/springframework/core/annotation/AnnotationsScanner.java#L85)
> Refactor apply method as unified one public method

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/TupleLikeElementsProperty.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/TypeReference.java
Map 의 속성은 key, value 2개의 속성을 N 개 가집니다.
N 개의 속성을 하나의 element 로 묶을 property 가 필요하여 TupleLkieElementsProperty 를 추가합니다.
- Map 의 element 는 2개의 속성을 가진 TupleLikeElementProperty 를 N 개 가집니다.
- Pair 의 element 는 2개의 속성을 가진 TupleLikeElementProperty 를 1개 가집니다.
> Introduce TupleLikeElementsProperty

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryNode.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTestSpecs.java
`@Size` 에서 max를 설정하지 않는 경우 `Integer.MAX_VALUE`를 설정하여 OOM이 발생하는 문제를 해결합니다
> Fix OOM when annotated size without max

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryExpression.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ContainerSizeManipulator.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/PriorityManipulator.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ComplexManipulatorTest.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ComplexManipulatorTestSpecs.java
`Apply` 연산을 `MetaManipulator` 구현체로 변경하면서 생긴 우선순위 정렬 문제를 해결합니다.
`PriorityManipulator`는 Priority 값을 기준으로 정렬을 진행하고, 구현체간 정렬 기준은 별도로 정의가 필요한 경우 override하여 구현합니다.
> Fix PriorityManipulator implementations sorting

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt
- fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGeneratorsTest.kt
ExpressionGenerator 구현을 리팩토링합니다.
ExpList를 직접 사용하는 케이스 처리를 위해 `.`에 대한 처리를 수정하였습니다.
`.`이 들어가는 경우에는 `DotExpressionGenerator`가 처리합니다.
`ParsedExpressionGenerator`와 같이 이름이 모호한 클래스도 `JoinExpressionGenerator`와 같이 의도가 명확한 이름으로 변경했습니다.
> Refactor Exp expressionGenerator

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ManipulatorOptimizer.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/OptimizedManipulatorResult.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/ManipulatorOptimizerTest.java
`BuilderManipulator` 을 입력했을 때 DBMS의 쿼리 옵티마이저처럼 최적의 쿼리를 만들어주는 역할을 가진 `ManipulatorOptimizer`를 추가합니다.
현재 BuilderManipulator를 상속하는 인터페이스와 구현체들이 명확하게 나누어지지 않고 불필요하게 복잡한 구조를 가지고 있어 다음 PR에서 `@Deprecate` 마킹과 함께 정리를 할 예정입니다.
> Add ManipulatorOptimizer

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryBuilder.java
신규 ArbitraryBuilder 에서 이전 ArbitraryBuilder 를 상속합니다.
타입을 맞춰 FixtureMonkey 객체에서 사용하는 버전에 따라 선택적으로 ArbitraryBuilder 를 생성하고 반환해서 사용하기 위함입니다.
신규 ArbitararyBuilder 에서는 재구현한 public 메소드들을 Override 해서 구현해야 하며, 신규에서 제공하지 않을 메소드는 `@Deprecated` 
후 UnsupportedException 을 던지도록 Override 하면 됩니다.
> Extends old ArbitraryBuilder

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/FieldProperty.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyDescriptorProperty.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/TypeCache.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java
Field 나 PropertyDescriptor 에서 getAnnotatedType 메소드는 매번 AnnotatedType 객체를 생성하므로 Cache 합니다.
> Introduce TypeCache

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt
ExpressionGenerator를 입력받는 `xxxExp` 확장함수를 추가합니다.
> Add remain Exp extensions

- build.gradle
- fixture-monkey-kotlin/build.gradle
Java toolchain을 적용합니다.
이후 JDK16 record 생성을 지원하는 모듈을 추가할 때 사용할 예정입니다.
> Apply gradle Java toolchain

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryNode.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTraverser.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTree.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
traverse의 결과로 만들어진 트리를 root인 ArbitraryNode에 직접 접근하여 조회하는 대신 ArbitraryTree 객체를 통해 조회하도록 수정합니다.
ArbitraryTree에서는 다음과 같은 역할을 합니다.
1. 표현식에 해당하는 ArbitraryNode 조회
2. Arbitrary 생성
> Add ArbitraryTree for encapsulating

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ContainerArbitraryPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/EntryArbitraryPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/MapArbitraryPropertyGenerator.java
ElementProperty는 항상 index가 존재해야할 것 같은데요, @Nullable로 처리되있어서 제거합니다.
혹시 nullable로 설정하신 이유가 있을까요??
> Set ElementProperty index null when container is set or map

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryOption.java
isExceptGeneratablePackage()의 primitive 확인 코드를 수정하고, 패키지 없이 생성된 클래스의 경우 true를 리턴하도록 코드를 추가했습니다.
> Fix isExceptGeneratablePackage primitive check error

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ApplyNodeCountManipulator.java
연산을 적용할 노드 개수를 제한하는 NodeManipulator를 추가합니다.
기존 limit과 같은 동작을 합니다.
노드 최대 개수는 int로도 충분할 것 같아 long에서 int로 변경합니다.
> Add ApplyNodeCountManipulator

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java
builderManipulators와 같은 내부 구현이 드러나지 않기 위해 `fixed`를 사용해서 동일한 동작 (apply)를 구현합니다.
> Refactor apply for better readability

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/AbstractArbitrarySet.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryNode.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitrarySetLazyValue.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/SimpleManipulatorTest.java
기존 0.3.X 버젼의 FixtureMonkey ArbitraryBuilder에 setLazy 연산을 추가합니다. (0.4.X에서 사용 가능하도록)
다른 부분은 기존 0.3.X setLazy 코드를 그대로 가져왔는데 
값으로 set하는것과 Arbitrary로 set하는 것을 모두 지원하기 위해서 코드를 추가/수정한 부분이 있습니다.
코멘트 단 곳들 문제없을지 한번 확인해주시면 감사하겠습니다!
> Add ArbitrarySetLazyValue

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/DefaultIterableSpec.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/SimpleManipulatorTest.java
Resolve #323 
IterableSpec any에서 size를 지정하지 않았을 때 ( 혹은 min , max 중 하나만 지정한 경우 ) , 발생하는 문제를 해결하였습니다.
#323 이슈에서 언급되었던 `Arbitraries.longs().between(this.minSize, this.maxSize).sample();` 코드는 39179a10a91be65e9a8a1883715748460869b6c8 에서 수정되었음을 확인했습니다.
따라서 다른 곳에서 문제점이 있음을 인지하고, 파악하였으며 파악한 문제점은 아래와 같습니다.
1. random에 의해 limit이 0으로 설정되었을 때, `ArbitrarySet` 클래스의 `getApplicableValue()`에 의해  sample이 생성되지 않는 경우
- 리스트에 any에서 할당한 값이 설정되지 않는 경우
2. max가 설정되지 않고, min은 설정되었지만 min이 `DEFAULT_ELEMENT_MAX_SIZE`보다 큰 경우
- boundary 관련 exception이 발생하는 경우
3. max, min이 둘 다 설정되지 않았을 때, `DEFAULT_ELEMENT_MIN_SIZE` 에 의해 size가 0인 list가 반환되는 경우
- 반환된 리스트가 빈 리스트인 경우
위 3가지 문제를 해결하고, 테스트 코드를 추가하였습니다.
> Fix NullPointerException when using IterableSpec any()

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpec.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/InnerSpecTest.java
InnerSpec의 key(consumer), value(consumer) 메소드를 사용하여 entry를 추가할 때 각각 해당 entry의 value, key 노드는 설정할 수 없는 문제가 있었습니다.
이를 해결하기 위해 consumer를 받는 새로운 entry 메소드 2개를 추가합니다.
- **entry(Object key, Consumer<InnerSpec> consumer)**: key가 설정된 Entry추가, value는 consumer로 설정
- **entry(Consumer<InnerSpec> consumer, @Nullable Object value)**: value가 설정된 entry추가, key는 consumer로 설정
> Add InnerSpec entry

- .github/workflows/build.yml
- Remove JDK 16 from job matrix
- Support LTS version of JDKs for efficiency. 
- Remove duplicated executions of SpotBugs, Checkstyle on every JDK versoins. 
- Change testing job names including 'JDK {version}', it makes more readability.
- Before : ![image](https://user-images.githubusercontent.com/910151/178132760-0d286945-fcd3-460a-9a4b-e555a621ae3b.png)
- After : ![image](https://user-images.githubusercontent.com/910151/178138706-04082c09-0ba2-46f5-b7e6-0108c9017b4f.png)
- Execute 'check' task, instead of 'build' task.
- This workflow does not need  'jar' files.
- Use gradle-build-action for more efficient caching.
- https://github.com/gradle/gradle-build-action#why-use-the-gradle-build-action 
- Add GtiHub Actions for reporting
- …
> Enhance checks and reporting by GitHub Actions

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsAdditionalTestSpecs.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
ArbitraryPropertyGenerator를 변경하는 옵션을 추가합니다.
insertFirst가 의미가 Stack의 연산인 `push`와 동일한 의미이고, 사용자 입장에서 표현이 간결한 것 같아 변경해보았습니다.
의견 부탁드립니다.
> Add ArbitraryPropertyGenerator options

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt
- fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGeneratorsTest.kt
Exp의 기본 입력 타입을 `KProperty` 으로 설정하고 Java Getter를 입력받는 경우는 suffix `Getter`를 붙여 
입력한 메소드 레퍼런스 타입의 ambiguity를 해결합니다.
> Refactor Exp for resolving ambiguity

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultArbitraryGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/JavaDefaultArbitraryGeneratorBuilder.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaArbitraryResolver.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeArbitraryResolver.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeTypeArbitraryGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/JavaTypeArbitraryGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptionsBuilder.java
- fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/generator/JavaDefaultArbitraryGeneratorTest.java
- fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/JavaTimeTypeArbitraryGeneratorTests.java
- fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationJavaArbitraryResolver.java
- fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationJavaTimeArbitraryResolver.java
- fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/plugin/JavaxValidationPlugin.java
- fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationArbitraryIntrospectorTest.java
- fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationTimeJavaArbitraryResolverTest.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
기본적인 자바 자료형 타입, 시간 타입을 변경할 수 있게 옵션을 추가합니다.
헷갈릴 수 있는 표현들을 정리합니다.
ex) 이전에는 `JavaxValidationArbitraryTypeIntrospector` 는 introspector임에도 Arbitrary를 직접 반환했습니다.
Arbitrary를 생성하여 반환합니다.
입력받은 Arbitrary를 변경하고 반환합니다.
`com.navercorp.fixturemonkey.resolver.ArbitraryResolver`  와 이름이 겹칩니다.
더 적절한 이름이 있으면 변경할 예정입니다.
ArbitraryGenerator + ArbitraryResolver 
항상 ArbitraryIntrospectorResult를 반환합니다.
> Add Java type ArbitraryGenerator options

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/OptionalArbitraryPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/StreamArbitraryPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/MapEntryElementProperty.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/TupleLikeElementsProperty.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/TypeReference.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java
Annotation이 없는 AnnotatedType을 생성하는 로직이 반복되어 utility method로 추가합니다.
> Add utility method for generating AnnotatedType without annotation

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/OldArbitraryBuilderImpl.java
putGenerator를 통해 ArbitraryGenerator를 변경했을 때 properyNameResolver가 정상적으로 동작하지 않는 문제를 해결합니다
> Fix propertyNameResolver error when putGenerator

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt
record 타입이 아닌 경우 getter에서 파싱한 프로퍼티 명의 첫글자가 대문자인 문제를 해결합니다.
기록차 남기고 바로 머지하겠습니다.
> Fix exp resolves property name when not record type

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java
DefaultArbitraryBuilder에서 copy()할 때 validOnly 값도 copy하도록 수정합니다.
> Fix copy to include validOnly

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/PropertyNameNodeResolver.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java
PropertyNameNodeResolver 에서 객체 내부 모든 필드를 가리키는 * 표현식을 처리하지 못하는 문제를 해결합니다.
- 관련 테스트: SimpleManipulatorTest.giveMeSetAllName
> Fix PropertyNameNodeResolver to match all index string

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/collection/IteratorCache.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/collection/LruCache.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/collection/StreamCache.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ElementProperty.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkey.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpec.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DecomposableContainerValue.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DecomposedContainerValueFactory.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultDecomposedContainerValueFactory.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ManipulateOptions.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ManipulateOptionsBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetDecomposedValueManipulator.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetLazyManipulator.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsAdditionalTestSpecs.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java
Iterator, Stream을 decompose하여 값을 설정할 수 있게 구조를 수정합니다.
`Iterator`, `Stream`은 한 번 사용하면 재사용할 수 없으므로 List로 변환하고 캐싱하여 사용합니다.
값을 decompose할 때는 `List`로 변환해서 처리합니다.
> Refactor decompose iterator, stream

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt
boolean 타입의 이름에서 `is`를 제거하지 않고 그대로 반환하는 문제를 해결합니다.
> Fix ExpressionGenerator returns boolean without is

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ContainerElementNodeResolver.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/MetadataCollector.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeKeyValueResolver.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeLastEntryResolver.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeNullityManipulator.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/PropertyNameNodeResolver.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/RootNodeResolver.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
register를 했을 때 중첩되는 객체가 무시되지 않도록 순서를 조정합니다.
상위 노드에 있는 노드를 항상 먼저 조회합니다.
> Fix register apply order

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/EnumIntrospector.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java
코틀린에서 타입 추론시 컴파일러에서 와일드카드를 넣을 수 있습니다.
와일드카드가 들어간 경우에도 Enum을 생성할 수 있도록 EnumIntrospector를 수정합니다.
> Fix enumIntrospector works with wildcard

- fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationJavaArbitraryResolver.java
- fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/BigDecimalIntrospectorSpec.java
- fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/BigIntegerIntrospectorSpec.java
- fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/FloatIntrospectorSpec.java
- fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationArbitraryIntrospectorTest.java
- fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationJavaArbitraryResolverTest.java
- fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/LongIntrospectorSpec.java
JavaxValidationJavaArbitraryResolver 에서 미구현되어 있던 메소드들을 구현합니다.
- doubles, floats, longs, bigIntegers, bigDecimals
> Add javax validation arbitrary for missing numerical types

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitrarySet.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitrarySetArbitrary.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitrarySetLazyValue.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitrarySetPostCondition.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/ExpressionSpec.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/BuilderManipulatorAdapter.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetDecomposedValueManipulator.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/SpecTest.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/SpecTestSpecs.java
0.4.0 버젼에서 ExpressionSpec을 사용한 .spec(), .specAny() 연산을 쓸 수 있도록 기능을 추가합니다.
- BuilderManipulatorAdapter를 사용해 ExpressionSpec의 BuilderManipulator들을 0.4.0 버젼에서 사용할 수 있는 연산의 형태로 변환합니다.
> Add spec for DefaultArbitraryBuilder 

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/RootProperty.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkey.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryBuilderContext.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTree.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/MonkeyContext.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/MonkeyContextBuilder.java
동일한 LabMonkey에서 생성한 경우 캐싱이 적용이 됩니다.
캐싱은 Property의 타입과 어노테이션을 기준으로 적용합니다.
연산을 적용한 경우 캐싱을 적용하지 않습니다.
> Add global caching

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTraverser.java
컨테이너인 경우 필드는 존재하지 않으므로 항상 `SingleValueObjectPropertyGenerator`를 사용하도록 수정합니다.
> Refactor how container ObjectProperty generating

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetDecomposedValueManipulator.java
컨테이너를 decompose할 때 mapEntry가 nullInject로 인해 null이 되는 문제를 해결합니다.
> Add set not null inject when set decomposed

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetDecomposedValueManipulator.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
필드를 null로 Fixed 되는 경우에 필드의 하위 필드를 설정할 수 없는 문제를 해결합니다.
> Fix set when fixed as null

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
기본 자바 패키지에 존재하는 객체는 `SingleValueObjectPropertyGenerator`로 생성하도록 수정합니다.
ex) URI 등등
> Fix generate Java default classes by SingleValueObjectPropertyGenerator

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptionsBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTree.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
jqwik의 `injectDuplicate`가 unique함을 보장하지 않아서 unique 연산을 제거합니다.
0.4.0 배포 이후에 Arbitrary에 의존하지 않고 Unique한 값을 만들어 내는 구조를 고민해볼 예정입니다.
> Remove uniqueProperties

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/KPropertyProperty.kt
- fixture-monkey-kotlin/src/test/java/com/navercorp/fixturemonkey/kotlin/spec/JavaObject.java
- fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyV04JavaTest.kt
- fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/test/PrimaryConstructorArbitraryIntrospectorTest.kt
java와 kotlin 혼용 시 kotlin plugin을 활성화하면 java 객체를 생성 못하는 이슈를 해결합니다.
> Add support for KPropertyProperty

- fixture-monkey-jackson/build.gradle
0.4.2 배포하려다가 취약점 있던 게 기억나서 배포를 잠시 미루고 내일 하려고합니다.
큰 이슈는 없겠지만 호환성 문제가 있을 수 있어 테스트를 진행하고 배포하려고 합니다.
0.4.2에서 사용하던 jackson 2.13.3이 DoS에 취약하다고 합니다.
https://security.snyk.io/package/maven/com.fasterxml.jackson.core:jackson-databind/2.13.3
> Upgrade jackson version

- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonArbitraryIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/plugin/JacksonPlugin.java
- fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04JacksonTest.java
타입을 생성할 때 하위 타입 중 하나를 jackson이 아닌 introspector로 생성을 할경우 이슈가 생겨 revert 합니다.
0.4.3에서 객체 생성 방식 변경하면서 같이 지원하는 게 좋을 것 같습니다.
> Remove supporting @JsonSubTypes, @JsonTypeInfo

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultContainerPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultSingleContainerPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java
Generics 가 직접 노출되지 않은 컨테이너 타입의 Property 생성을 디폴트 타입(String)으로 정의되도록 지원합니다.
> Enhance DefaultContainerPropertyGenerator with no generics container

- fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationConstraintGenerator.java
- fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationConstraintGeneratorTest.java
- fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/introspector/ShortIntrospectorSpec.java
javax validation 에서 숫자 타입(Long, Integer, Short, Byte)의 min, max 값 추출시 타입 MIN, MAX 값 바운더리를 반영한다.
> Enhance min max constraint for integer type

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/OldArbitraryBuilderImpl.java
0.3 Fixture Monkey 인스턴스를 통해 생성하는 경우 `putGenerator`를 통해 ArbitraryGenerator를 변경하면 ArbitraryGenerator에 해당하는 propertyNameResolver가 적용안되는 문제를 해결합니다.
> Fix not resolved properly

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/arbitrary/ArbitraryValue.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryValue.java
ArbitraryValue 는 Memoize 에서 cache 되는 대상이 아니므로, Memoize 에 cache 되지 않도록 false 로 메소드를 구현합니다.
> Implements false isGeneratorMemoizable for ArbitraryValue

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/CompositeProperty.java
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/generator/KotlinPropertyGenerator.kt
- fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyExtensionsTest.kt
- fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyV04KotlinJacksonTest.kt
Kotlin reflection 의 memberProperties 는 상위 부모의 private 속성 값을 property 로 가져오지 못합니다.
KotlinPlugin 상위 부모의 private 속성값이 누락되어 값 제어가 되지 않습니다.
이에 따라 KotlinPlugin 의 properties 를 구할 때 java properties 와 조합한 결과를 반환합니다.
> Fix Kotlin properties with parent private property

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapEntryElementIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/SetIntrospector.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkey.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
1. register로 설정한 ArbitraryBuilder에서 apply를 적용할 경우 size가 실행 안되는 문제를 해결합니다
2. Map의 Value인 객체의 필드에 Set이 존재할 경우 entry마다 uniqueSet을 공유하여 unique하게 생성하지 못하는 문제를 해결합니다.
> Fix for compatible 0.4.3

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/MapContainerPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/SetContainerPropertyGenerator.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
EnumMap or EnumSet size which generated by FixtureMonkey  would not exceed enum size if no `size` manipulation
https://github.com/naver/fixture-monkey/issues/487
> Fix generating enum set or map

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyGeneratorContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorContext.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
`Map<?, Map<?, ? >` 같은 형태일 때 유니크함을 보장할 수 없는 문제를 해결합니다.
resolves #419
> Fix nested map generates entry uniquely

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeSetDecomposedValueManipulator.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java
Fix set interface as value
resolves #494 
`setInterface`
> Fix set interface as value

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpec.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/InnerSpecTest.java
InnerSpec의 연산들이 entry를 생성하지 않도록 수정합니다.
InnerSpec에서 다른 연산과 다르게 다음 연산들은 entry를 만들고 있습니다.
`InnerSpec value(Consumer<InnerSpec> consumer) `,
`InnerSpec entry(Consumer<InnerSpec> consumer, @Nullable Object value)`
다른 연산들과 일관성을 맞춰 entry를 생성하지 않도록 수정합니다.
> Fix innerSpec manipulations not generate entry

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BeanArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FieldReflectionArbitraryIntrospector.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/BeanArbitraryGenerator.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/generator/FieldReflectionArbitraryGenerator.java
Related to #35
Remove usage of `org.junit.platform.commons.logging.Logger`
> Replace junit logger to slf4j logger

- .github/workflows/build.yml
외부 contributor는 action을 정상적으로 실행할 수 없으므로 제거합니다.
report만 action에서 확인할 수 없고 검증은 `Execute check without tests` 에서 실행합니다.
> Remove checkStyle, spotBugs report

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/InterfaceObjectPropertyGenerator.java
- fixture-monkey-mockito/src/test/java/com/navercorp/fixturemonkey/mockito/plugin/MockitoPluginTest.java
- fixture-monkey-mockito/src/test/java/com/navercorp/fixturemonkey/mockito/plugin/MockitoPluginTestSpecs.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/LabMonkeyBuilder.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsAdditionalTestSpecs.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04OptionsTest.java
인터페이스가 반환할 구현체를 명시하는 옵션을 추가합니다.
`interfaceImplements`
resolves #348
> Add a simple option for generating concrete class with interface

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
`set` compatible for ExpressionSpec
* `setSpec`
> Add set compatible for ExpressionSpec

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTraverser.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/TraverseContext.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04Test.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyV04TestSpecs.java
Add generating a circular-reference object
순환참조일 경우 1-depth까지만 생성합니다.
For example,
```java
class A {
B b;
}
class B {
A a;
}
A a = fixture.giveMeOne(A.class);
```
```json
{
"b" :  {
"a" : {
"b" : null
}
}
}
```
* `sampleSelfRecursiveObject`
* `sampleSelfRecursiveList`
* `sampleRecursiveObject`
resolves #495
> Add generating a circular-reference object

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/MonkeyManipulatorFactory.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/OldArbitraryBuilderImpl.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ManipulatorSet.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpec.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/InnerSpecTest.java
Refactors InnerSpec
InnerSpec no longer depends on `ArbitraryTraverser` and `ManipulateOptions`. `MonkeyManipulatorFactory` now has the responsibility to create `NodeManipulator`s.
> Refactor InnerSpec

- .github/workflows/build.yml
- .github/workflows/deploy.yml
Updated workflows to cache dependencies using [actions/setup-java](https://github.com/actions/setup-java#caching-packages-dependencies). `setup-java@v3` or newer has caching **built-in**.
Jobs on GitHub-hosted runners start in a clean virtual environment and **must download dependencies each time**, causing increased network utilization, longer runtime, and increased cost. To help speed up the time it takes to recreate files like dependencies, GitHub can cache files that frequently use in workflows.
Java projects can run faster on GitHub Actions by enabling dependency caching on the [setup-java](https://github.com/actions/setup-java) action. `setup-java` supports caching for both Gradle and Maven projects.
**AS-IS**
```yaml
- name: Set up JDK
uses: actions/setup-java@v2
with: …
```
> Use setup-java action to cache dependencies

- fixture-monkey-jakarta-validation/src/main/java/com/navercorp/fixturemonkey/jakarta/validation/introspector/JakartaValidationJavaArbitraryResolver.java
- fixture-monkey-jakarta-validation/src/test/java/com/navercorp/fixturemonkey/jakarta/validation/JakartaValidationFixtureMonkeyTest.java
- fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationJavaArbitraryResolver.java
- fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/JavaxValidationFixtureMonkeyTest.java
Fix #553 
Add a condition to not include [control characters](https://en.wikipedia.org/wiki/Control_character) when creating String values through `XXXValidationJavaArbitraryResolver`.
Add additional assertions to existing test code
> Add a condition to not include control characters when creating String values (#553)

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/MonkeyManipulatorFactory.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ManipulatorSet.java
Refactor `DefaultArbitraryBuilder` to use `MonkeyManipulatorFactory` when generating NodeManipulators.
Passes all the existing test cases.
> Refactor DefaultArbitraryBuilder to use MonkeyManipulatorFactory

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ContainerInfoManipulator.java
Refactor matching logic in ContainerInfoManipulator
NextNodePredicate 개수가 parentArbitraryProperties와 다르더라도 사용할 수 있는 매칭 알고리즘으로 변경합니다.
역순으로 조회하면서 매칭 여부를 확인합니다.
현재 NextNodePredicate 개수가 parentArbitraryProperties와 다른 경우는 register에서 size 연산을 사용하는 경우입니다.
> Refactor matching logic in ContainerInfoManipulator

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGeneratorExtensions.kt
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt
- fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGeneratorJavaTestSpecs.java
- fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGeneratorsTest.kt
- fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/test/KotlinExpJacksonPropertyTest.kt
Add JoinableExpressionGenerator for Exp
Removing class `Exp`, `ExpList`
Splitting ExpressionGenerators into `ExpressionGeneratorExtensions` and `ExpressionGenerators` for better readability
> Add JoinableExpressionGenerator interface

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/CompositeNodeResolver.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTestSpecs.java
Fix flatten node resolvers when distinct
표현식에서 Exp 객체 두개가 있을 때, 두 개를 합치면  `IdentityNodeResolver`를 포함하는 문제를 해결합니다.
* sizeThirdNestedNested
> Fix flatten node resolvers when distinct

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpec.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTraverser.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ContainerElementPredicate.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ContainerInfoManipulator.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultNodeResolver.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/IdentityNodeResolver.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NextNodePredicate.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeAllElementPredicate.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeElementPredicate.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeKeyPredicate.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/NodeValuePredicate.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/PropertyPredicate.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/StartNodePredicate.java
Refactor ContainerInfoManipulator removing useless dependencies
Remove useless dependencies in a `NextNodePredicate` interface.
It only depends on `ObjectProperty`
> Refactor ContainerInfoManipulator

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ChildArbitraryContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArrayIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BeanArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BuilderArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ConstructorPropertiesArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/EntryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FieldReflectionArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ListIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapEntryElementIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/OptionalIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/QueueIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/SetIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/StreamIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/TupleLikeElementsIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonArbitraryIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JsonNodeIntrospector.java
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/PrimaryConstructorArbitraryIntrospector.kt
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsAdditionalTestSpecs.java
Refactor ArbitraryGeneratorContext returns Arbitrary lazily
Only property in use would be resolved.
Make getter of ChildArbitraryContext private 
> Refactor ArbitraryGeneratorContext returns Arbitrary lazily

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptions.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/GenerateOptionsBuilder.java
- fixture-monkey-jakarta-validation/src/main/java/com/navercorp/fixturemonkey/jakarta/validation/generator/JakartaValidationArbitraryContainerInfoGenerator.java
- fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/generator/JavaxValidationArbitraryContainerInfoGenerator.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/InnerSpecTest.java
Fix #569 
Replace `defaultArbitraryContainerInfo` to `defaultArbitraryContainerInfoGenerator`
None
The maintainers [provided guidelines](https://github.com/naver/fixture-monkey/issues/569#issuecomment-1428916871) for doing this.
Unfortunately, I don't think I understood this properly. I worked on it first, but I'm honestly not sure if my work went in the right direction 😞 
Regarding this bug, I don't think it's good for a discovered bug to remain for a long time.
So it would be nice to proceed with fixing the bug at the maintainer's discretion.
> Replace defaultArbitraryContainerInfo to defaultArbitraryContainerInfoGenerator

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryNode.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTraverser.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsAdditionalTestSpecs.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java
Refactor ArbitraryNode not unique
It leads to performance issue if ArbitraryNode is unique.
It could be many `ArbitraryNodes` with same property name.
* samePropertyDiffImplementations
> Refactor ArbitraryNode not unique

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyContextBuilder.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ChildArbitraryContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/CombinableArbitrary.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultArbitraryGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/FilteredCombinableArbitrary.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/FixedCombinableArbitrary.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/LazyCombinableArbitrary.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/MappedCombinableArbitrary.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/NullInjectCombinableArbitrary.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryIntrospectorResult.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArrayIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BeanArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BooleanIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BuilderArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ConstructorPropertiesArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FieldReflectionArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/IteratorIntrospector.java
- fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/ArbitraryIntrospectorResultTest.java
- fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/introspector/CompositeArbitraryIntrospectorTest.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonArbitraryIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonCombinableArbitrary.java
- fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyJacksonTest.java
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/PrimaryConstructorArbitraryIntrospector.kt
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryTree.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java
Add CombinableArbitrary for adding metadata when generating an object
객체를 생성할 때 메타 데이터가 필요한 경우가 있습니다.
ex. Jackson에서 `@JsonSubTypes`, `@JsonTypeInfo`를 사용해 추상 타입을 추론할 때 필요한 `@type` 필드
생성하고 객체로 바로 변환하지 않고 필드와 메타데이터를 가지고 있는 객체를 반환하고
사용자가 최종적으로 사용할 때 객체로 변환하도록 합니다.
> Add CombinableArbitrary for adding metadata

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ConstructorParameterPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/FieldPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/JavaBeansPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BeanArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FieldReflectionArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyCache.java
- fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/property/PropertyCacheTest.java
- fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/type/TypesTest.java
Refactor improving generation of properties
* FieldPropertyGenerator
* JavaBeansPropertyGenerator
* ConstructorParameterPropertyGenerator
* `getPropertyDescriptors` to `getPropertyDescriptorsByPropertyName`
* `getFields` to `getFieldsByName`
* `getConstructorProperties` to `getConstructorParameterPropertiesByParameterName`
> Refactor improving generation of properties

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ChildArbitraryContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/FilteredCombinableArbitrary.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/MappedCombinableArbitrary.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/NullInjectCombinableArbitrary.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArrayIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyDescriptorProperty.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonArbitraryIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/plugin/JacksonPlugin.java
- fixture-monkey-tests/java-tests/build.gradle
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JacksonSpecs.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JacksonTest.java
Add support for @JsonTypeInfo and @JsonSubTypes
* `ChildArbitraryContext#getArbitraries` returns rawValue of CombinableArbitrary
* CombinableArbitrary applies filter, map to rawValue
* jsonTypeInfoName
* jsonTypeInfoList
* jsonTypeInfoIdClass
* jsonTypeWithAnnotations
* jsonTypeWithAnnotationsList
* jsonTypeInfoListInSetter
* jsonTypeInfoListIncludeWrapperObject
* jsonTypeInfoListInSetterIncludeWrapperObject
* jsonTypeWithAnnotationsIncludeWrapperObjectList
> Add support for @JsonTypeInfo and @JsonSubTypes

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/KotlinPlugin.kt
Fix generating Kotlin sealed class
For type like `? extends SealedClass`
> Fix generating Kotlin sealed class

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/InnerSpec.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/InnerSpecTest.java
Resolves #602
Adds keys(), values(), and entries() methods to Innerspec to support setting multiple values at once.
Added related tests to `InnerSpecTest`.
> Add Innerspec keys(), values(), entries()

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ChildArbitraryContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArrayIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonArbitraryIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/plugin/JacksonPlugin.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JacksonTest.java
Remove supporting @JsonTypeInfo, @JsonSubTypes
In order to support `@JsonTypeInfo`, `@JsonSubTypes`, we should consider these situations.
1. generating `List<JsonSuperType>`
* It should be a `raw` value in `ListIntrospector` 
* Other introspectors (excluding `JacksonArbitraryIntrospector`) should be `combined` value.
2. Sub-introspector is `JacksonArbitraryIntrospector`, but super-introspector is not `JacksonArbitraryIntrospector`
> Remove supporting @JsonTypeInfo, @JsonSubTypes

- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/ImmutableJavaTestSpecs.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JacksonTest.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java
Fix FixtureCustomizer in Jackson
* Interface `ArbitraryBuilder` customize could work in any property types.
* It would be combined when customized
> Fix FixtureCustomizer in Jackson

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ChildArbitraryContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArrayIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/EntryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ListIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapEntryElementIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapEntryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/OptionalIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/QueueIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/SetIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/StreamIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/TupleLikeElementsIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonArbitraryIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonArrayArbitraryIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonCollectionArbitraryIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonCombinableArbitrary.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonMapArbitraryIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonObjectArbitraryIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JsonNodeIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/plugin/JacksonPlugin.java
- fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/JacksonRecordTest.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JacksonTest.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsAdditionalTestSpecs.java
Add JacksonContainerIntrospector
Jackson deserializes `Container type` by its own way.
Add `JacksonCollectionArbitraryIntrospector`, `JacksonArrayArbitraryIntrospector`, `JacksonMapArbitraryIntrospector`
* sampleContainerType
* sampleListType
* fixedListType
* sampleSetType
* fixedSetType
* sampleArrayType
* fixedArrayType
* sampleOptionalType
* fixedOptionalType
* sampleMapType
* fixedMapType
* sampleMapEntryType
* fixedMapEntryType
> Add JacksonContainerIntrospector

- fixture-monkey-api/build.gradle
- fixture-monkey-jakarta-validation/build.gradle
- fixture-monkey-starter/build.gradle
- fixture-monkey/build.gradle
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryValue.java
Polish for jakarta-validation
* remove redundant dependency and useless dependency
* using Exception instead of concrete class `ConstraintViolationException`, `jakarta.validation.ConstraintViolationException`. It may fail if client uses lower version of `hibernate-validator`
> Polish jakarta-validation dependency

- .github/workflows/benchmark.yml
- .github/workflows/build.yml
Bump up GitHub Action `gradle-build-action`
Due to security vulnerability.
> Bump up GitHub Action gradle-build-action

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ArbitraryBuilderExtensions.kt
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/InnerSpecTest.kt
I want to use like this (in kotlin).
```kotlin
val actual = SUT.giveMeBuilder<Map<String, String>>()
.setInner {
it.keys("key1", "key2")
.minSize(3)
}
.sample()
```
InnerSpecTest#innerConsumer
> Add setInner method takes InnerSpec consumer

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/KPropertyProperty.kt
- fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/property/KPropertyPropertyTest.kt
The original implementation of the `getValue()` function of `KPropertyProperty` gives a NPE when a kotlin property does not have a backing field.
The refactored implementation replaces the check for `kProperty.isAccessible` with a check for the accessibility of the getter javaMethod.
`getValueOfPropertyWithoutBackingField()` test added.
> Fix KPropertyProperty getValue

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/resolver/ArbitraryBuilderCandidateListExtensions.kt
related #628
Change the target class of extension methods. (ArbitraryBuilderCandidateFactory -> ArbitraryBuilderCandidateList)
- `ArbitraryBuilderCandidateFactory` 는 static method 여서 extension 의 의미가 없습니다
- `ArbitraryBuilderCandidateList` 에 대한 extension 을 추가합니다
> Improve ArbitraryBuilderCandidateListExtensions

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java
Change return type of `DefaultArbitraryBuilder` with `ArbitraryBuilder`.
We have the `ArbitraryBuilder` interface. It seems better to use it.
Regression test
> Return ArbitraryBuilder instead of DefaultArbitraryBuilder

- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryBuilderContext.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/DefaultArbitraryBuilder.java
Enhance `fixed` performance
`fixed` would not trigger sampling immediately.
One ArbitraryBuilder would `sample` only once.
> Enhance fixed performance

- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonArrayArbitraryIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonCollectionArbitraryIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonMapArbitraryIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonObjectArbitraryIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/type/JacksonTypeReference.java
- fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyJacksonTest.java
Fix generating nested generic type in Jackson
* sampleGenericObject
* sampleListNestedElement
* sampleMapNestedListValue
* sampleGenericArray
> Fix generating nested generic type in Jackson

- assets/js/custom-java-highlight.js
- assets/js/highlight.js
- assets/jsconfig.json
- assets/scss/app.scss
- config/_default/menus/menus.en.toml
- content/en/docs/customizing-objects/_index.md
- content/en/docs/customizing-objects/apis.md
- content/en/docs/customizing-objects/arbitrary.md
- content/en/docs/customizing-objects/expressions.md
- content/en/docs/customizing-objects/innerspec.md
- content/en/docs/fixture-monkey-options/_index.md
- content/en/docs/generating-objects/_index.md
- content/en/docs/get-started/_index.md
- content/en/docs/get-started/creating-objects-in-kotlin.md
- content/en/docs/get-started/creating-test-objects-without-lombok.md
- content/en/docs/get-started/creating-test-objects.md
- content/en/docs/plugins/_index.md
- layouts/index.html
- package-lock.json
- package.json
Adding customizing-objects sections for Fixture Monkey documentation version 2.
- Using highlight.js to highlight code syntax (needs more adjustment)
- Adding customizing-objects section
To view the new document in your local environment,
checkout to the branch and run npm install, followed by npm run
(or the Demo is up here: https://sookim1110.github.io/fixture-monkey/ -> Recommend viewing it in an incognito/private tab as there might be cached files.)
> Add Doc v2 Customizing Objects Section

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FieldReflectionArbitraryIntrospector.java
Fix omit if setting field is failed with `FieldReflectionArbitraryIntrospector`
I think It is better to log instead of failing when facing the issue Fixture Monkey could not deal with.
> Fix omit if setting field is failed with FieldReflectionArbitraryIntrospector

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultObjectPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/NoArgumentInterfaceJavaMethodPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/CompositePropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ConstructorParameterPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/DefaultPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/FieldPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/JavaBeansPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyGenerator.java
- fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/generator/ArbitraryPropertyTest.java
- fixture-monkey-jackson/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyExpressionGeneratorTest.java
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/generator/InterfaceKFunctionPropertyGenerator.kt
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/KotlinPropertyCache.kt
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/KotlinPropertyGenerator.kt
- fixture-monkey-kotlin/src/test/kotlin/com/navercorp/fixturemonkey/kotlin/property/KotlinPropertyCacheTest.kt
Refactor removing annotatedType dependency in PropertyGenerator interface
Remove direct dependency with `AnnotatedType`
> Refactor removing annotatedType dependency in PropertyGenerator interface

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/PrimaryConstructorArbitraryIntrospector.kt
- fixture-monkey-tests/kotlin-concurrent-tests/build.gradle
- fixture-monkey-tests/kotlin-concurrent-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/concurrent/kotlin/ConcurrentTest.kt
- fixture-monkey-tests/kotlin-concurrent-tests/src/test/resources/junit-platform.properties
- settings.gradle
Fix Kotlin PrimaryConstructorArbitraryIntrospector generates concurretly
* tests in ConcurrentTest
> Fix Kotlin PrimaryConstructorArbitraryIntrospector generates concurretly

- config/_default/menus/menus.en.toml
- config/_default/params.toml
- content/en/docs/customizing-objects/apis.md
- content/en/docs/customizing-objects/expressions.md
- content/en/docs/fixture-monkey-options/options.md
- content/en/docs/generating-objects/fixture-monkey.md
- content/en/docs/generating-objects/introspector.md
- content/en/docs/get-started/adding-bean-validation.md
- content/en/docs/get-started/creating-objects-in-kotlin.md
- content/en/docs/get-started/customizing objects.md
- content/en/docs/get-started/requirements.md
- content/en/docs/intellij-plugin/_index.md
- content/en/docs/intellij-plugin/fixture-monkey-helper.md
- content/en/docs/introduction/overview.md
- content/en/docs/plugins/_index.md
- content/en/docs/plugins/jackson-plugin/_index.md
- content/en/docs/plugins/jackson-plugin/features.md
- content/en/docs/plugins/jackson-plugin/jackson-annotations.md
- content/en/docs/plugins/jackson-plugin/jackson-object-arbitrary-introspector.md
- content/en/docs/plugins/jakarta-validation-plugin/_index.md
- content/en/docs/plugins/jakarta-validation-plugin/bean-validation.md
- content/en/docs/plugins/jakarta-validation-plugin/features.md
- content/en/docs/plugins/kotlin-plugin/_index.md
- content/en/docs/plugins/kotlin-plugin/features.md
- content/en/docs/plugins/kotlin-plugin/introspectors-for-kotlin.md
- content/en/docs/plugins/kotlin-plugin/kotlin-exp.md
- layouts/shortcodes/fixture-monkey-version.html
Adding Generating Objects Section & Plugins Section for Fixture Monkey documentation version 2.
- Adding generating-objects section
- Adding plugins section (jakarta-validation, kotlin, jackson)
- Adding intellij plugin section
To view the new document in your local environment,
checkout to the branch and run npm install, followed by npm run
> Add Generating Objects Section & Plugins Section

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ValidateArbitraryGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptions.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java
- fixture-monkey-jakarta-validation/src/test/java/com/navercorp/fixturemonkey/jakarta/validation/JakartaValidationFixtureMonkeyTest.java
- fixture-monkey-javax-validation/src/test/java/com/navercorp/fixturemonkey/javax/validation/JavaxValidationFixtureMonkeyTest.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/AnnotationTest.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/ValidationAnnotationTestSpecs.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java
Fix ArbitraryBuilder without validOnly sampling
* sampleNotValidAnnotation
> Fix ArbitraryBuilder without validOnly sampling

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/instantiator/KotlinInstantiatorDsl.kt
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/InstantiatorTest.kt
Add instantiate DSL factory method for root type
* instantiateByCompanionObjectFactoryMethodWithoutType
* instantiateByCompanionObjectFactoryMethodWithoutTypeWithParameter
> Add instantiate DSL factory method for root type

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/experimental/JavaGetterPropertySelector.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java
Refactor JavaGetterPropertySelector referencing container by index, allIndex
* setJavaGetterCollection
* setJavaGetterCollectionAllElement
> Refactor JavaGetterPropertySelector referencing container by index, allIndex

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/DefaultPropertyGenerator.java
- fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/ConstructorPropertiesRecordTest.java
- fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/RecordTestSpecs.java
Fix generating record constructor properties
* sampleTwoConstructorsRecord
* fixedTwoConstructorsRecord
* sampleNoArgsConstructorRecord
* fixedNoArgsConstructorRecord
> Fix generating record constructor properties

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/jqwik/ArbitraryUtils.java
Fix a jqwik concurrent execution issue due to StoreRepository
Since we are just using a jqwik as an engine to generate basic types, StoreRepository is not needed.
> Fix a jqwik concurrent execution issue due to StoreRepository

- build.gradle
- fixture-monkey-api/build.gradle
- fixture-monkey-autoparams/build.gradle
- fixture-monkey-engine/build.gradle
- fixture-monkey-jackson/build.gradle
- fixture-monkey-jakarta-validation/build.gradle
- fixture-monkey-javax-validation/build.gradle
- fixture-monkey-junit-jupiter/build.gradle
- fixture-monkey-kotlin/build.gradle
- fixture-monkey-mockito/build.gradle
- fixture-monkey-starter-kotlin/build.gradle
- fixture-monkey-starter/build.gradle
- fixture-monkey-tests/build.gradle
- fixture-monkey-tests/java-tests/build.gradle
- fixture-monkey/build.gradle
- gradle/wrapper/gradle-wrapper.properties
Upgrade gradle 8.4 version for supporting JDK21
- disable `editorConfig`
- upgrade jacoco  0.8.7 -> 0.8.11
- upgrade lombok 1.8.26 -> 1.8.30
- upgrade jmh 1.35 -> 1.37
- upgrade jmh plugin 0.6.6 -> 0.7.2
- remove retry plugin
- upgrade assertj 3.22.0 -> 3.24.2
> Upgrade gradle 8.4 version for supporting JDK21

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/PrimaryConstructorArbitraryIntrospector.kt
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/InstantiatorTest.kt
This is a pr regarding the issue at
https://github.com/naver/fixture-monkey/issues/847
i have made modification to`PrimaryConstructorArbitraryIntrospector` to include that handles private access.
additionaly added a corresponding test case.
check through test case
> kotlin private primary constructor access

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/JavaDefaultArbitraryGeneratorBuilder.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/plugin/InterfacePlugin.java
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/OptionTest.kt
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java
Add a Plugin to extend interfaces
All interface related options are separated into `InterfacePlugin`.
* anonymousArbitraryIntrospector
* notUseAnonymousArbitraryIntrospector
> Add a Plugin to extend interfaces

- .github/PULL_REQUEST_TEMPLATE.md
Specify to update the corresponding document page within the PR in the PR template.
This will ensure the documentation stays up-to-date.
> Add document update check to PR update

- docs/content/v1.0.x/release-notes/_index.md
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/NullArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptions.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java
Fix addExceptGenerateClass option to not be affected by specific ArbitraryIntrospector
* addExceptGenerateClass
Yes
> Fix addExceptGenerateClass option to not be affected by specific ArbitraryIntrospector

- docs/content/v1.0.x/release-notes/_index.md
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java
- fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/type/TypesTest.java
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
Fix setting object field by any other type
* setToObject
Yes
> Fix setting object field by any other type

- docs/content/v1.0.x/release-notes/_index.md
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/AnonymousArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BeanArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BuilderArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ConstructorPropertiesArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FieldReflectionArbitraryIntrospector.java
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/PrimaryConstructorArbitraryIntrospector.kt
- fixture-monkey-tests/kotlin-tests/build.gradle.kts
- fixture-monkey-tests/kotlin-tests/src/test/java/com/navercorp/fixturemonkey/tests/kotlin/BuilderJavaTestSpecs.java
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
Refactor does not throw exception when it cannot generate
The next ArbitraryIntrospector will be used
* primaryConstructorArbitraryIntrospectorNotThrows
* beanArbitraryIntrospectorNotThrows
* constructorPropertiesArbitraryIntrospectorNotThrows
* anonymousArbitraryIntrospectorNotThrows
* builderArbitraryIntrospectorNotThrows
* builderArbitraryIntrospectorMissBuildMethodNotThrows
Yes
> Refactor does not throw exception when it cannot generate

- docs/content/v1.0.x/release-notes/_index.md
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ArrayIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BooleanIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/IterableIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/IteratorIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ListIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapEntryElementIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapEntryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/MapIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/QueueIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/SetIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/StreamIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/UuidIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/DoubleGenericTypeMatcher.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/matcher/SingleGenericTypeMatcher.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/Types.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonArrayArbitraryIntrospector.java
- fixture-monkey-jackson/src/main/java/com/navercorp/fixturemonkey/jackson/introspector/JacksonCollectionArbitraryIntrospector.java
Add logging when using invalid ArbitraryIntrospector
* logs when container type.
* throws an exception if the concrete type.
No
> Add handling when using invalid ArbitraryIntrospector

- docs/content/v1.0.x/release-notes/_index.md
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BeanArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FieldReflectionArbitraryIntrospector.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/NoArgsConstructorJavaTestSpecs.java
Fix mutation of a generated object by FieldReflection, BeanArbitraryIntrospector
* beanArbitraryIntrospectorSampleTwiceResultNotMutated
* fieldReflectionArbitraryIntrospectorSampleTwiceResultNotMutated
Yes
> Fix mutation of a generated object by FieldReflection, BeanArbitraryIntrospector

- docs/content/v1.0.x-kor/docs/generating-objects/fixture-monkey.md
Translating the fixture-monkey page of generating-objects section into Korean
related to https://github.com/naver/fixture-monkey/issues/864
The process of creating a fixureMonkey instance for creating a text fixture was documented.
I copied the English document and then compared it one by one and translated it.
We do not update the document because it is a request for Korean translation.
> Add fixture-monkey page of generating-objects section for kor doc

- docs/content/v1.0.x/docs/get-started/creating-objects-in-kotlin.md
- docs/content/v1.0.x/docs/plugins/kotlin-plugin/features.md
- docs/content/v1.0.x/docs/plugins/kotlin-plugin/kotlin-exp.md
- fix wrong markdown link in docs
- change dependency name for kotlin starter in docs
> Fix typo in docs

- docs/content/v1.0.x-kor/docs/generating-objects/generating-complex-types.md
Translating generating-complex-types page of generating-objects section into Korean
related to https://github.com/naver/fixture-monkey/issues/864
We were translating about how to create a complex object. 
There were two lines of text to translate.
Using command `npm start`
We do not update the document because it is a request for Korean translation.
> Add generating-complex-types page of generating-objects section for kor doc

- docs/content/v1.0.x/docs/generating-objects/instantiate-methods.md
We found a typo and fixed it.
Fixed a word. Changed the word written as `Constuctor` to `Constructor`.
Only words were modified.
This is not a case of modifying, so I didn't proceed.
> Fix typo in docs

- docs/content/v1.0.x/release-notes/_index.md
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/plugin/InterfacePlugin.java
- fixture-monkey-mockito/src/test/java/com/navercorp/fixturemonkey/mockito/plugin/MockitoPluginTest.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java
Add InterfacePlugin supports abstract classes
* sampleSelfRecursiveAbstract
* setConcreteList
* setConcreteClassWhenHasNoParentValue
* setConcreteClassWhenHasParentValue
* setConcreteListWithNoParentValue
* sampleConcreteWhenHasSameNameProperty
* interfaceImplementsAndMockitoAbstract
Yes
> Add InterfacePlugin supports abstract class

- docs/content/v1.0.x-kor/docs/get-started/adding-bean-validation.md
- docs/content/v1.0.x/docs/get-started/adding-bean-validation.md
Translate the Adding Bean validation page into Korean.
related : #864 
Interprets the title and description of the Adding Bean Validation page
You can test it with `npm start`
> Add Adding Bean Validation page of get-started section for kor doc

- fixture-monkey-api/build.gradle.kts
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/jqwik/JqwikJavaArbitraryResolver.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/random/RegexGenerator.java
- fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/random/RegexGeneratorTest.java
- fixture-monkey/build.gradle.kts
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ResolvedCombinableArbitrary.java
Related to #772, #713
Changes the regular expression generation library to RgxGen.
- An exception is thrown when RgxGen fails to generate or takes more than 10 seconds.
- The option of generating random values(or null) when RgxGen fails was considered but not implemented because the fixture generation will still fail at the `ArbitaryValidator`
- Some of the cases mentioned in the referenced issues (`^[\\S]+$`, `\\S+`) are now generatable. However, cases like `^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{8,20}$` fails to be generated because the library has limitations (https://github.com/curious-odd-man/RgxGen?tab=readme-ov-file#limitations). 
Added RegexGeneratorTest.
Will add a subsequent commit to update the document once this PR is reviewed and finalized.
> Change regular expression generation library to RgxGen

- docs/content/v1.0.x-kor/docs/generating-objects/introspector.md
Translating introspector page of generating-objects section into Korean
related to https://github.com/naver/fixture-monkey/issues/864
Using command `npm start`
We do not update the document because it is a request for Korean translation.
> Add introspector page of generating-objects section for kor doc

- docs/content/v1.0.x/release-notes/_index.md
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeSetLazyManipulator.java
Fix setLazy with value wrapped by Just would not be manipulated
* setLazyJustNotChanged
yes
> Fix setLazy with value wrapped by Just would not be manipulated

- fixture-monkey-tests/java-17-tests/build.gradle
- fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/InterfaceDefaultMethodTest.java
- fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/JacksonRecordTest.java
- fixture-monkey-tests/java-concurrent-tests/build.gradle
- fixture-monkey-tests/java-tests/build.gradle.kts
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/AnonymousInstanceTest.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/ImmutableJavaTestSpecs.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JacksonSpecs.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JacksonTest.java
Add java conventions plugin to `fixture-monkey-tests` and fix failing checkstyle.
Checkstyle test passes.
No update necessary.
> Add java conventions plugin to fixture-monkey-tests

- docs/content/v1.0.x/release-notes/_index.md
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/TypedArbitraryIntrospector.java
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/PrimaryConstructorArbitraryIntrospector.kt
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/ConstructorTestSpecs.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
Fix missing required PropertyGenerator within introspectors
* pushPrimaryConstructorIntrospector
* fieldAndConstructorParameterMismatch
Yes
> Fix missing required PropertyGenerator within introspectors

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/PrimaryConstructorArbitraryIntrospector.kt
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/ValueClassTest.kt
1. an access to private constructor has been added when resolving value class properties 
2. test cases for the fix above
test cases added for a class with a value class property with the private primary constructor.
> add access to the private primary constructor for value class properties

- docs/content/v1.0.x/docs/get-started/creating-objects-in-kotlin.md
Kotlin uses `Int` instead of `Integer`, but I will fix the parts of the Kotlin example that are written as `Integer`.
In my opinion, this is more Kotlin-like.
> fix: Change Java Integer type to Int type in Kotlin

- docs/content/v1.0.x-kor/docs/get-started/creating-objects-in-kotlin.md
- docs/content/v1.0.x/docs/get-started/creating-objects-in-kotlin.md
kor translation
related to #864 
~~translation for kor docs including incorrect parts of original.~~
~~as follow:~~
~~`fixture-monkey-kotlin-starter` => `fixture-monkey-starter-kotlin`~~
~~If modifications to the original text should not be included in this PR, I will revert, and seperate~~
When I checked the main branch, I realized that it was already fixed, but not rebased in kor-translation.
> Add creating-objects-in-kotlin page of get-started section for kor doc

- docs/content/v1.0.x-kor/docs/fixture-monkey-options/concepts.md
['Concept'](https://naver.github.io/fixture-monkey/docs/fixture-monkey-options/concepts/#property) page of 'Fixture Monkey Options' section related to #864 
If you find something awkward or something we can improve, please comment.
thank you.
> Add 'Concept' page of 'Fixture Monkey Options' section for kor doc

- docs/layouts/index.html
공백 문자열로 인해 Get Started 페이지로 링크가 되지 않는 점을 수정하였습니다.
로컬 환경 구동 테스트
> Fix the missing href link on the 'Get Started' button on the main page

- docs/content/v1.0.x/release-notes/_index.md
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/JdkVariantOptions.java
- fixture-monkey-api/src/main/java17/com/navercorp/fixturemonkey/api/generator/SealedTypeObjectPropertyGenerator.java
- fixture-monkey-api/src/main/java17/com/navercorp/fixturemonkey/api/option/JdkVariantOptions.java
- fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/SealedClassTest.java
Add supporting for sealed class and sealed interface
* sampleSealedClass
* sampleSealedInterface
* sampleSealedClassProperty
* fixedSealedClassProperty
Yes
> Add supporting for sealed class and sealed interface

- docs/layouts/partials/footer/script-footer.html
It seems that there is an update related to RelPermalink in the latest Hugo version. The request URLs for JavaScript files are incorrectly mapped. 
The issue is being addressed by fixing it to use Permalink instead.
> Fix doc RelPermalink

- docs/content/v1.0.x-kor/docs/fixture-monkey-options/customization-options.md
- docs/content/v1.0.x-kor/docs/fixture-monkey-options/generation-options.md
- docs/content/v1.0.x-kor/docs/fixture-monkey-options/other-options.md
related to https://github.com/naver/fixture-monkey/issues/864
`Fixture Monkey Options`의 `Generation Options`, `Customization Options`, `Other Options page` 한국어 번역
---
`Generation Options page`의 [46번 째](https://naver.github.io/fixture-monkey/docs/fixture-monkey-options/generation-options/#arbitrary-generation), [75번 째 줄](https://naver.github.io/fixture-monkey/docs/fixture-monkey-options/generation-options/#arbitrary-generation-1)의 Arbitrary Generation 파트 제목이 중복되는 것 같습니다.
추가적으로 어색한 부분이나 개선할 점 있으면 comment 부탁드립니다. 감사합니다 :)
> Add 'Fixture Monkey Options' section for kor doc

- docs/content/v1.0.x-kor/docs/plugins/kotest-plugin/features.md
- docs/content/v1.0.x-kor/docs/plugins/kotest-plugin/property-based-testing.md
Translate `Features`, `Kotest Property Based Testing`  page of plugin/kotest-plugin section.
This korean translation works is related to #864
Tested with npm start to check translations of docs.
1. I had some concerns about translation of `generator` as 생성자.
2. Same as translation of `input` as 입력.
> Translate kotest-plugin section title and contents

- docs/content/v1.0.x-kor/docs/plugins/kotlin-plugin/introspectors-for-kotlin.md
Translation of kotlin-plugin/introspectors-for-kotlin for Koreans.
This korean translation works is related to #864.
Tested with `npm start` to check translations of docs.
`kotlin-plugin/introspectors-for-kotlin` document is updated.
> Translation of kotlin-plugin/introspectors-for-kotlin document

- docs/content/v1.0.x-kor/docs/plugins/kotlin-plugin/kotlin-exp.md
Translation of kotlin-plugin/kotlin-exp for Koreans.
This korean translation works is related to #864.
Tested with `npm start` to check translations of docs.
`kotlin-plugin/kotlin-exp` document is updated.
> [translate] kotlin-plugin/kotlin-exp to korean

- docs/content/v1.0.x-kor/docs/cheat-sheet/faq.md
Translated ``FAQ`` page of cheat-sheet section 
this pull request is related to #864 
Tested with ``npm start`` to check translations of docs and links.
I had some questions while translating the document regarding tone, word choice and possible typo.
- need suggestions for better translated word choices
-  ``customize`` to ``커스터마이징`` or ``사용자 지정``
-  is there any convention for translating the word ``fixture``? please let me know.
- awkward the tone of translated question , I thought it would be more natural if we could use ``해야 할까요?``or ``하나요?``
- possible missing period at the last sentence of the original document ( For more information, check the [`thenApply()` section](../../customizing-objects/apis/#thenapply) ...), or was this on purpose?
> Translate cheat-sheet faq section title and contents

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ConstructorProperty.java
Fix ConstructorProperty equals and hashCode using Type instead of AnnotatedType
In general, implementations of `AnnotatedType` do not override `equals` and `hashCode`.
existing tests
No
> Fix ConstructorProperty equals and hashCode using Type instead of AnnotatedType

- docs/config/_default/config.toml
- docs/config/_default/languages.toml
- docs/config/_default/menus/menus.v1-0-0-kor.toml
- docs/content/v1.0.x-kor/docs/plugins/kotest-plugin/_index.md
- docs/layouts/partials/header/header.html
Resolves #957
- Fix `Get started` button to go to korean translation.
- Remain the content url when changing language.
> Fix Korean document bugs

- docs/content/v1.0.x-kor/release-notes/_index.md
- docs/content/v1.0.x/release-notes/_index.md
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeSetDecomposedValueManipulator.java
Fix setting a child of a concrete type to an abstract type
* setConcreteTypeChildReturnsExactlyConcreteTypeChildType
Yes
> Fix setting a child of a concrete type to an abstract type

- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
`AbstractThrowableAssert#getCause()` method was deprecated and changed to `AbstractThrowableAssert#cause()`.
The git action execution history confirmed the use of a deprecated function. `AbstractThrowableAssert#getCause()` method was deprecated and changed to `AbstractThrowableAssert#cause()`. When I checked the method, there was no change behavior and the name change seemed to be the purpose.
Tested in `KotlinTest#kotlinObjectUseJavaGetterThrows`.
There are no feature changes.
> Remove the deprecated getCause function in KotlinTest class

- docs/content/v1.0.x-kor/release-notes/_index.md
- docs/content/v1.0.x/release-notes/_index.md
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/JavaDefaultArbitraryGeneratorBuilder.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ListIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/SingleGenericCollectionIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptions.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/CandidateConcretePropertyResolver.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/CompositeCandidateConcretePropertyResolver.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ConcreteTypeCandidateConcretePropertyResolver.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/DefaultCandidateConcretePropertyResolver.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyUtils.java
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ArbitraryTraverser.java
Add resolve the candidate concrete type of container type
It only resolves the concrete type of the container type, it can resolve the object type after 1.1.0. 
* propertyCandidateResolverReturnsConcreteListType
* nestedPropertyCandidateResolverReturnsConcreteListType
* propertyCandidateResolverReturnsConcreteSetType
* nestedPropertyCandidateResolverReturnsConcreteSetType
Yes
> Add resolve the candidate concrete type of container type

- docs/content/v1.0.x-kor/release-notes/_index.md
- docs/content/v1.0.x/release-notes/_index.md
There is a difference between English and Korean document release notes.
**ASIS - In English Docs**
- Add `ConcreteTypeDefinition` in `ArbitraryProperty`, deprecate `getChildPropertiesByResolvedProperty` and `getChildPropertyListsByCandidateProperty` which is added in 1.0.14.
- Fix setting a child of a concrete type to an abstract type.
- Add a new Kotlin Exp expression for referencing root. ex. `set(String::root, "expected")`
**ASIS - In Korean Docs**
- Add `ConcreteTypeDefinition` in `ArbitraryProperty`, deprecate `getChildPropertiesByResolvedProperty` and `getChildPropertyListsByCandidateProperty` which is added in 1.0.14.
- Add "KotlinDurationIntrospector" supporting generating a Duration type in Kotlin.
- Add a new Kotlin Exp expression for referencing root. ex. `set(String::root, …
> synchronize 1.0.15 version change history

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/plugin/SimpleValueJqwikPlugin.java
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/SimpleValueJqwikPluginTest.kt
*Describe what feature is implemented by this PR.*
*If there is a related issue, write the issue number and link*
Resolves #986 
Fixed a problem with the order of parameters injected when creating an instance of `SimpleValueJqwikPlugin` in the `accept()` method within the `SimpleValueJqwikPlugin` class.
to verify the scenario that was reproduced in the #986 issue.
> Fix simple value plugin constuctor

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/plugin/SimpleValueJqwikPlugin.java
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/SimpleValueJqwikPluginTest.kt
Fix "out of byte range" issue by modifying SimpleValueJqwikPlugin to limit byte value generation to within Byte.MIN_VALUE and Byte.MAX_VALUE.
This PR addresses the issue where byte values generated by SimpleValueJqwikPlugin could exceed the valid range of Byte.MIN_VALUE and Byte.MAX_VALUE. The plugin has been modified to ensure byte values are constrained within this range.
The changes have been tested by adding a new unit test, sampleSetObjectByte, which ensures that byte values generated by SimpleValueJqwikPlugin are within the range of Byte.MIN_VALUE and Byte.MAX_VALUE.
> Fix a SimpleValuePlugin "out of byte range" error

- docs/content/v1.0.x-kor/release-notes/_index.md
- docs/content/v1.0.x/release-notes/_index.md
- fixture-monkey-api/src/main/java17/com/navercorp/fixturemonkey/api/option/JdkVariantOptions.java
- fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/JacksonRecordTest.java
- fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/RecordTestSpecs.java
- fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/SealedClassTest.java
An enum instance with abstract method treated as a sealed class.
So, its properties are generated by the `SealedTypeObjectPropertyGenerator`, resulting in an unexpected generation failure.
- JacksonRecordTest#sampleEnum
- SealedClassTest#sampleEnum
Yes
> Fix generation of enum implementations as a sealed class in JDK17

- docs/content/v1.0.x-kor/release-notes/_index.md
- docs/content/v1.0.x/release-notes/_index.md
- fixture-monkey-api/src/main/java17/com/navercorp/fixturemonkey/api/generator/SealedTypeObjectPropertyGenerator.java
- fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/MultiLevelSealedClassTest.java
- fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/SealedClassTest.java
- fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/SealedClassTestSpecs.java
Add support for multi-level inheritance of sealed class and sealed interface.
Add a new test that adds an intermediate inherited class and interface to an existing test.
> Add support multi-level inheritance of sealed

- docs/content/v1.0.x-kor/release-notes/_index.md
- docs/content/v1.0.x/release-notes/_index.md
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java
- fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/JdkVariantOptionsTest.java
Fix when to apply JdkVariantOptions in FixtureMonkeyOptionsBuilder.
Fix an issue where JdkVariantOptions.apply has a higher priority than options set by the user because it is in the build method of FixtureMonkeyOptionsBuilder.
Use existing tests.
> Fix when to apply JdkVariantOptions

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/InterfaceObjectPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ObjectPropertyGeneratorContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/SingleValueObjectPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/InterfaceCandidateConcretePropertyResolver.java
- fixture-monkey-api/src/main/java17/com/navercorp/fixturemonkey/api/generator/SealedTypeObjectPropertyGenerator.java
- fixture-monkey-api/src/main/java17/com/navercorp/fixturemonkey/api/property/SealedTypeCandidateConcretePropertyResolver.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ArbitraryTraverser.java
Deprecate the ObjectPropertyGenerators that modify child properties listed below.
- InterfaceObjectPropertyGenerator
- SingleValueObjectPropertyGenerator
- SealedTypeObjectPropertyGenerator
They are replaced by the implementations of `CandidateConcretePropertyResolver`
existing tests
No
> Deprecate the ObjectPropertyGenerators that modify child properties

- fixture-monkey-api/src/main/java17/com/navercorp/fixturemonkey/api/option/JdkVariantOptions.java
Fix set ZoneId in Kotlin JDK21
It is only tested locally because it requires a Kotlin version upgrade.
It'll be in 1.0.21 release commit
> Fix set ZoneId in Kotlin JDK21

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/SingleGenericCollectionIntrospector.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java
Fix collection generation not throw exception
- collectionNotThrows
It'll be in 1.0.21 release commit
> Fix collection generation not throw exception

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/container/DefaultDecomposedContainerValueFactory.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/FunctionalInterfaceContainerPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FunctionalInterfaceArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/KotlinPlugin.kt
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/ImmutableFunctionalInterfaceSpecs.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeSetDecomposedValueManipulator.java
Fix decompose Java Kotlin functional interface
* decomposeKotlinLambdaReturnType
* decomposeKotlinLambdaOnlyReturnType
* decomposeSupplierObject
* decomposeFunctionObject
Not Yet
> Fix decompose Java Kotlin functional interface

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryProperty.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/DefaultObjectPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ObjectProperty.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptions.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/plugin/InterfacePlugin.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ArbitraryTraverser.java
Add compatibility with ObjectPropertyGenerator and CandidateConcretePropertyResolver
ObjectPropetyGenerator will not resolve the child properties and the candidate concrete property.
To remove the concrete type of `ObjectPropetyGenerator` from 1.1.0, make ObjectPropertyGenerator and CandidateConcretePropertyResolver compatible.
> Add compatibility with ObjectPropertyGenerator and CandidateConcretePropertyResolver

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyExtensions.kt
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/ArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/JavaTypeDefaultTypeArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/NodeCustomizerManipulator.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/experimental/ExperimentalArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectNode.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java
Refactor customizeProperty works in order
ArbitraryBuilder API `customizeProperty` is affected by order from 1.1.0.
For example, the results of two examples are different.
```kotlin
.setExp(StringValue::value, "abcdef")
.customizeProperty(typedString<String>("value")) {
it.map { str -> str.substring(0..2) }
}
result -> `abc`
```
```kotlin
.customizeProperty(typedString<String>("value")) {
it.filter { value -> value.length > 5 }
}
.setExp(StringValue::value, "fixed")
result -> "fixed"
```
* customizePropertyAfterSet
* customizePropertyIgnoredIfSet
Later
> Refactor customizeProperty works in order

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/PrimaryConstructorArbitraryIntrospector.kt
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/CircularReferenceTestSpecs.kt
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
Fix for generating Kotlin self-reference with default arguments
* circularReferenceDefaultArgument
* circularReferenceNullable
It'll be another PR
> Fix for generating Kotlin self-reference with default arguments

- docs/config/_default/params.toml
- docs/content/v1.0.x-kor/docs/get-started/requirements.md
- docs/content/v1.0.x/docs/get-started/requirements.md
- fixture-monkey/src/main/resources/junit-platform.properties
Add a requirements of JUnit platform Launcher and remove .jqwik-database
Yes
> Add a requirements of JUnit platform Launcher and remove .jqwik-database

- docs/content/v1.0.x-kor/docs/generating-objects/introspector.md
#1037
한글 버전 공식 문서의 `Introspector` 페이지에서 `"만약 final이 아닌 변수가 선언되어 있다면 getter 또는 setter 없이도 사용 가능합니다."`의 내용이 `FieldReflectionArbitrary` 아래가 아닌 `BuilderArbitraryIntrospector` 아래에 위치해있습니다. 
해당 부분을 `FieldReflectionArbitrary` 아래에 위치하도록 파일을 수정했습니다.
(※영문 파일은 정상이며, 한글 파일만 위치가 잘못되어 있기 때문에 한글 파일만을 수정했습니다.)
yes
> Fix doc introspector description

- docs/content/v1.0.x-kor/release-notes/_index.md
- docs/content/v1.0.x/release-notes/_index.md
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/MonkeyStringArbitrary.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/jqwik/ArbitraryUtils.java
Fix concurrency issue with string generation
Yes
> Fix concurrency issue with string generation

- README.md
FixtureMonkey를 공유하는 개인 아티클 링크를 추가했습니다.
단순히 FixtureMonkey를 사용하는 방법을 넘어서 구체적인 동작 원리에 대해서 소개합니다.
해당 아티클은 위키 형태로, 이후 더 많은 내용이 담길 예정입니다.
> Docs: Add articles

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/MonkeyStringArbitrary.java
- fixture-monkey-api/src/test/java/com/navercorp/fixturemonkey/api/arbitrary/MonkeyStringArbitraryTest.java
fixture-monkey-api에서 문자열 한국어 범위 지정 메서드를 추가했습니다.
테스트 객체 생성 시 문자열 내 한글만을 작성해야 하는 경우를 위한 메서드 추가입니다.
문자열 난수를 생성해주는 MonkeyStringArbitrary 내에 korean 메서드를 추가했고,
유니코드 상 한글의 첫글자('가')부터 끝글자('힣')를 범위로 지정했습니다.
```java
public StringArbitrary korean() {
this.characterArbitrary = this.characterArbitrary.range('가', '힣');
return this;
}
```
`new MonkeyStringArbitrary().korean()`를 정의해, 샘플 문자의 범위를 테스트했습니다.
code style에 맞는 자동 포맷팅 셋업을 알고 싶습니다.
- 빌드 시 항상 깨지는 걸 수작업으로 변경하기 어렵기 때문입니다.
> Feat: korean method in MonkeyStringArbitrary

- docs/content/v1.0.x-kor/docs/cheat-sheet/faq.md
- docs/content/v1.0.x-kor/docs/generating-objects/introspector.md
- docs/content/v1.0.x-kor/release-notes/_index.md
- docs/content/v1.0.x/docs/cheat-sheet/faq.md
- docs/content/v1.0.x/docs/generating-objects/introspector.md
- docs/content/v1.0.x/release-notes/_index.md
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ConstructorArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/PriorityConstructorArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ConstructorParameterPropertyGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/type/TypeCache.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/ImmutableGenericTypeSpecs.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/PriorityConstructorArbitraryIntrospectorTest.java
Add PriorityConstructorArbitraryIntrospector
- PriorityConstructorArbitraryIntrospectorTest#sample
- PriorityConstructorArbitraryIntrospectorTest#setWithoutName
- PriorityConstructorArbitraryIntrospectorTest#sample
- PriorityConstructorArbitraryIntrospectorTest#set
- PriorityConstructorArbitraryIntrospectorTest#genericType
- PriorityConstructorArbitraryIntrospectorTest#twoGenericType
- PriorityConstructorArbitraryIntrospectorTest#twoGenericObjectConstructorParameterOrderDiff
- PriorityConstructorArbitraryIntrospectorTest#twoGenericObjectConstructorParameterOrderDiffNameDiff
Yes
> Add PriorityConstructorArbitraryIntrospector

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/ObjectBuilder.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyContextBuilder.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyGeneratorContext.java
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryBuilderContext.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/MonkeyManipulatorFactory.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectNode.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/TraverseContext.java
Refactor scoped context
Each component has a context and contexts have a hierarchy. A child context has a reference to the parent context, the parent context does not have a reference to the child context.
- FixtureMonkey → `MonkeyContext`
- ArbitrayBuilder → `ArbitraryBuilderContext`
- ObjectTree → `TraverseContext`
No needed
> Refactor scoped context

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BeanArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FieldReflectionArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/DefaultPropertyGenerator.java
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/KotlinConstructorParameterPropertyGenerator.kt
Add caching properties to improve performance
- existing tests
No needed
> Add caching properties to improve performance

- docs/content/v1.0.x-kor/docs/generating-objects/introspector.md
- docs/content/v1.0.x-kor/release-notes/_index.md
- docs/content/v1.0.x/docs/generating-objects/introspector.md
- docs/content/v1.0.x/release-notes/_index.md
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FailoverIntrospector.java
Add **enableLoggingFail** option to the `FailoverIntrospector`
yes
> Add enableLoggingFail option to the FailoverIntrospector

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ArbitraryGeneratorLoggingContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BeanArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/BuilderArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/ConstructorPropertiesArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FailoverIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/introspector/FieldReflectionArbitraryIntrospector.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptions.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptionsBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java
add enableLoggingFail option for failed introspect warning log.
[#1066](https://github.com/naver/fixture-monkey/issues/1066)
* I used `||` due to overlapping parts with the existing `enableLoggingFail` option in the `FailoverIntrospector`.
* I also think it overlaps with the existing `enableLoggingFail` option, so I have omitted it for now.
> Add enableLoggingFail option for failed introspect to FixtureMonkeyOptions

- docs/content/v1.1.x-kor/release-notes/_index.md
- docs/content/v1.1.x/release-notes/_index.md
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyExtensions.kt
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryBuilderContextProvider.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/JavaTypeDefaultTypeArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/MonkeyManipulatorFactory.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java
Fix a bug in registering JavaBuilder and KotlinBuilder
- registerJavaTypebuilder
- registerKotlinTypeBuilder
After merge https://github.com/naver/fixture-monkey/pull/1086
> Fix a bug in registering JavaBuilder and KotlinBuilder

- docs/content/v1.1.x-kor/docs/migration-guide/migration-guide.md
- docs/content/v1.1.x/docs/migration-guide/migration-guide.md
[#1084](https://github.com/naver/fixture-monkey/issues/1084)
replace `giveMeBuilder` with `giveMeKotlinBuilder` in section `How to use Kotlin ArbiraryBuilder APIs` of v1.1.x migration-guide
Yes
> Fix 'How to use Kotlin ArbitraryBuilder APIs' in 1.1.x migration guide

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/context/MonkeyContextBuilder.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ContainerPropertyGeneratorContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ObjectProperty.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ObjectPropertyGeneratorContext.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ComparableRootProperty.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/PropertyPath.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/TreeRootProperty.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/tree/DefaultTraverseNode.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/tree/TraverseNodeMetadata.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ResolvedCombinableArbitrary.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectNode.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTree.java
Add TreeRootProperty
TreeRootProperty is the interface to reference the root node of the object tree.
It may be field or java beans getter or type parameter etc.
Not yet
> Refactor add TreeRootProperty

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/option/FixtureMonkeyOptions.java
Remove default FixtureMonkeyOptions
It may be the breaking change. But it compels me for the following reasons.
1. The default `FixtureMonkeyOptions` initializes if added in dependency, it causes the unnecessary costs.
2. It forces the jqwik depenedency in `fixture-monkey-api` module. 
We'll recommend to use `FixtureMonkeyOptions.builder().build()` instead.
Later
> Remove default FixtureMonkeyOptions

- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectNode.java
Fix not applying registered child manipulations if parent uses thenApply
* parentRegisterThenApplyAndSizeReturnsChildRegister
Later
> Fix not applying registered child manipulations if parent uses thenApply

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/plugin/InterfacePlugin.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/InterfaceTestSpecs.java
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java
Fix abstractExtends in InterfacePlugin does not support interface
* abstractClassExtends
* abstractExtendsInterfaceThrows
* interfaceImplementsAbstractClassThrows
Later
> Fix abstractExtends in InterfacePlugin does not support interface

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/property/ConstructorParameterPropertyGenerator.java
- fixture-monkey-api/src/main/java17/com/navercorp/fixturemonkey/api/option/JdkVariantOptions.java
- fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/ConstructorPropertiesRecordTest.java
- fixture-monkey-tests/java-17-tests/src/test/java/com/navercorp/fixturemonkey/tests/java17/RecordTestSpecs.java
Fix a record instance generates canonical constructor properties
* sampleCanonicalConstructorRecord
Later
> Fix a record instance generates canonical constructor properties

- .github/workflows/build.yml
Update `actions/upload-artifact` from v3 to v4 due to GitHub's deprecation notice.
Related: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
- Changed `actions/upload-artifact@v3` to `actions/upload-artifact@v4`
- Added `overwrite: true` to maintain same artifact behavior as v3
Changes will be tested through this PR's workflow run.
No documentation updates required as this is an internal workflow change.
> Update actions/upload-artifact from v3 to v4

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/engine/EngineUtils.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/random/Randoms.java
- fixture-monkey-benchmarks/fixture-monkey-benchmark/src/jmh/java/com/navercorp/fixturemonkey/SeedBenchmark.java
- fixture-monkey-junit-jupiter/build.gradle.kts
- fixture-monkey-junit-jupiter/src/main/java/com/navercorp/fixturemonkey/junit/jupiter/extension/FixtureMonkeySeedExtension.java
- fixture-monkey-junit-jupiter/src/test/java/com/navercorp/fixturemonkey/junit/jupiter/extension/FixtureMonkeySeedExtensionTest.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java
Add support for deterministic testing with JUnit
Later
> Add support for deterministic testing with JUnit

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/introspector/PrimaryConstructorArbitraryIntrospector.kt
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/ObjectSpecs.kt
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/SealedClassTest.kt
Fix generate Kotlin object, sealed object instance
* generateObjectInstanceThrows
* sealedObject
* sealedObjectThenApply
Later
> Fix generate Kotlin object, sealed object instance

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/constraint/JavaIntegerConstraint.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/ValidateArbitraryGenerator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/jqwik/JqwikJavaArbitraryResolver.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/plugin/SimpleValueJqwikPlugin.java
- fixture-monkey-jakarta-validation/src/main/java/com/navercorp/fixturemonkey/jakarta/validation/introspector/JakartaValidationConstraintGenerator.java
- fixture-monkey-javax-validation/src/main/java/com/navercorp/fixturemonkey/javax/validation/introspector/JavaxValidationConstraintGenerator.java
- fixture-monkey-kotest/src/main/kotlin/com/navercorp/fixturemonkey/kotest/KotestArbitraryGeneratorSet.kt
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotestInJunitTest.kt
This PR simplifies the `JavaIntegerConstraint` structure by removing the separate positive and negative range handling, aligning with the recent decimal constraint implementation improvements in #1131. Additionally, it improves the handling of `@Digits` annotation for integer types.
Related issues:
Fixes #1153
This PR implements a simplification of the integer constraint structure and improves digit validation:
- Removed redundant fields by eliminating separate `positive`/`negative` range handling
- Replaced with a single `min`/`max` range representation:
```java
JavaIntegerConstraint(
@Nullable BigInteger min,
@Nullable BigInteger max
)
```
- Ensures uniform distribution across valid ranges
- Aligned `@Digits` validation behavior with Jakarta Validation's actual implementation
- Previous …
> Simplify JavaIntegerConstraint structure to align with decimal constraint improvements

- fixture-monkey-kotest/src/main/kotlin/com/navercorp/fixturemonkey/kotest/ArbExtension.kt
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/generator/InterfaceKFunctionPropertyGenerator.kt
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/instantiator/KotlinInstantiator.kt
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/property/InterfaceKFunctionProperty.kt
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/type/KotlinTypeExtensions.kt
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/type/KotlinTypes.kt
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/ValueClassTest.kt
Fix Kotlin type not directly using javaType due to `value class`
Later
> Fix Kotlin type not directly using javaType

- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyExtensions.kt
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkey.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryBuilderContext.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/ArbitraryBuilderContextProvider.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/DefaultArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/builder/JavaTypeDefaultTypeArbitraryBuilder.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/customizer/MonkeyManipulatorFactory.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/resolver/ArbitraryResolver.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/MetadataCollector.java
- fixture-monkey/src/main/java/com/navercorp/fixturemonkey/tree/ObjectTreeMetadata.java
- fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyOptionsTest.java
Refactor splits active context and standby contexts
Maintain consistency with the initialization and application of registering manipulators, which means that registered manipulators are resolved lazily.
No Needed
> Refactor splits active context and standby contexts

- docs/content/v1.1.x-kor/docs/customizing-objects/apis.md
- docs/content/v1.1.x/docs/customizing-objects/apis.md
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/expression/JavaGetterPropertySelector.java
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/ExpressionGenerators.kt
- fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/FixtureMonkeyExtensions.kt
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java
- fixture-monkey-tests/kotlin-tests/src/test/java/com/navercorp/fixturemonkey/tests/kotlin/ImmutableJavaTestSpecs.java
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotlinTest.kt
Add compatibility with TypedPropertySelector and path expression DSL
- typedJavaGetter
- nestedTypedJavaGetter
- indexTypedJavaGetter
- typedKotlinPropertySelector
- typedNestedKotlinPropertySelector
- typedJavaPropertySelector
- typedRootIsKotlinNestedJavaPropertySelector
- typedRootIsJavaNestedJavaPropertySelector
Later
> Add compatibility with TypedPropertySelector and path expression DSL

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/CombinableArbitrary.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/IntegerCombinableArbitrary.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/IntegerCombinableArbitraryDelegator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/jqwik/JqwikIntegerCombinableArbitrary.java
- fixture-monkey-api/src/main/resources/META-INF/services/com.navercorp.fixturemonkey.api.arbitrary.IntegerCombinableArbitrary
- fixture-monkey-kotest/src/main/kotlin/com/navercorp/fixturemonkey/kotest/KotestArbitraryGeneratorSet.kt
- fixture-monkey-kotest/src/main/kotlin/com/navercorp/fixturemonkey/kotest/KotestIntegerCombinableArbitrary.kt
- fixture-monkey-kotest/src/main/resources/META-INF/services/com.navercorp.fixturemonkey.api.arbitrary.IntegerCombinableArbitrary
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotestInJunitTest.kt
Add `IntegerCombinableArbitrary` to allow easy customization of randomly generated Integer values, similar to the existing `StringCombinableArbitrary`. (#1188)
providing below APIs to customize the randomly generated Integer
`.positive()` - only positive numbers
`.negative()` - only negative numbers
`.withRange(min, max)` - numbers within range
`.even()` - only even numbers
`.odd()` - only odd numbers
- `integerCombinableArbitraryIsJqwik`
- `integerCombinableArbitraryInjectNull`
- `integerCombinableArbitraryFilter`
- `integerCombinableArbitraryPositive`
- `integerCombinableArbitraryNegative`
- `integerCombinableArbitraryWithRange`
- `integerCombinableArbitraryWithRangeAndFilter`
- `integerCombinableArbitraryEven`
- `integerCombinableArbitraryOdd`
- …
> Add IntegerCombinableArbitrary for easy Integer customization

- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/CombinableArbitrary.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/StringCombinableArbitrary.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/arbitrary/StringCombinableArbitraryDelegator.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/jqwik/JqwikJavaTypeArbitraryGeneratorSet.java
- fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/jqwik/JqwikStringCombinableArbitrary.java
- fixture-monkey-api/src/main/resources/META-INF/services/com.navercorp.fixturemonkey.api.arbitrary.StringCombinableArbitrary
- fixture-monkey-kotest/src/main/kotlin/com/navercorp/fixturemonkey/kotest/KotestArbitraryGeneratorSet.kt
- fixture-monkey-kotest/src/main/kotlin/com/navercorp/fixturemonkey/kotest/KotestStringCombinableArbitrary.kt
- fixture-monkey-kotest/src/main/resources/META-INF/services/com.navercorp.fixturemonkey.api.arbitrary.StringCombinableArbitrary
- fixture-monkey-tests/java-tests/src/test/java/com/navercorp/fixturemonkey/tests/java/JavaTest.java
- fixture-monkey-tests/kotlin-tests/src/test/kotlin/com/navercorp/fixturemonkey/tests/kotlin/KotestInJunitTest.kt
Add StringCombinableArbitrary for easy efficient customisation
providing below APIs to customize the randomly generated String
- alphabetic
- korean
- ascii
- numeric
- pattern
- withLength
- withMinLength
- withMaxLength
* stringCombinableArbitraryIsJqwik
* stringCombinableArbitraryInjectNull
* stringCombinableArbitraryFilter
* stringCombinableArbitraryFilterCharacter
* stringCombinableArbitraryFilterCharacterAndFilter
* stringCombinableArbitraryNumeric
* stringCombinableArbitraryMap
* stringCombinableArbitraryKorean
* stringCombinableArbitraryAlphabet
* stringCombinableArbitraryLatterWins
* stringCombinableArbitrary
* stringCombinableArbitraryAscii
Later
> Add StringCombinableArbitrary for easy efficient customisation

- cursor/rules/fixture-monkey-test-writing-rule.mdc
This PR implements a Cursor IDE rule file for FixtureMonkey test writing guidelines to help developers write more
effective and consistent tests using FixtureMonkey patterns and best practices. (#1190)
Added `cursor/rules/fixture-monkey-test-writing-rule.mdc` that provides intelligent code suggestions for FixtureMonkey
usage, including:
- Method selection guidance (`giveMeOne()` vs` giveMeBuilder()` vs `giveMe()`)
- FixtureMonkey instance configuration best practices
- Object customization with `.set()`, `.size()`, and builder methods
- Support for complex objects, generic types, and collections
- Context-aware suggestions based on existing code patterns
> As required by issue #1190, this rule has been extensively tested across different project
Scenario: Simple POJO object creation
Test …
> Add Cursor Rule for Fixture Monkey Test Writing Guidelines

- fixture-monkey-jakarta-validation/src/main/java/com/navercorp/fixturemonkey/jakarta/validation/validator/JakartaArbitraryValidator.java
This PR modifies the `DefaultArbitrayValidator`, a typo present in the `ValidationFailedException` message within the `JakartaArbitraryValidator` class, to `DefaultArbitraryValidator`.
Related Issue: [#1216 ]
A typo in the string 'DefaultArbitrayValidators ConstructViolations. type: ..' used to generate 'ValidationFailedException' in the 'validate' method of the 'JakartaArbitraryValidator' file was found and corrected.
It is a string typo correction within the code, and does not affect the way separate functional tests and existing logic work.
N/A
> Fix Typo in JakartaArbitraryValidator ValidationFailedException message

- docs/content/v1.1.x-kor/docs/get-started/creating-objects.md
- docs/content/v1.1.x/docs/get-started/creating-objects.md
This PR fixes a broken link in the "Creating test objects" guide that pointed to a non-existent page.
The document contained a link to ../creating-objects-without-lombok, which led to a 404 error. This PR removes the broken link.
> Fix link in creating-objects.md

- .github/workflows/benchmark.yml
The benchmark workflow previously executed jobs sequentially, taking 33 minutes to complete.
so this pr refactors the workflow using strategy.matrix for parallel execution.
If the JMH plugin is applied in Gradle, it automatically generates a jmh task.
Since JMH executes each benchmark method sequentially, I split the benchmarks into seperate modules to enable parallel execution.
I also considered method-level parallel execution, but JMH runs sequentially by design to avoid side effects from CPU cache, GC, and JIt. etc. so I didn't apply it.
- this actions is to execute on push or pull request to main or release branch.
.
> Refactor benchmark.yml to run modules in parallel
